### ISSUE TITLE
Material Design Widgets: Wetter View - Selber Datenpunkt für Mond Lumi

### ISSUE THREAD

**Issue by Leviathan09** [Scrounger/ioBroker.vis-materialdesign#101]
Bei den Views Wetter_Mond_Day_1-5 ist unterhalb vom Mond für die Lumi immer der Datenpunkt für Tag 1 hinterlegt.

**Comment by Scrounger** [comment]
bug fix in 3651e39acb428bed1570173184375981c691553a
