### ISSUE TITLE
Material Design Widget "materialdesign - Button State Multi vertical": "CSS Font & Text" -> text-align"

### ISSUE THREAD

**Issue by ice987987** [Scrounger/ioBroker.vis-materialdesign#104]
Material Design Widget "materialdesign - Button State Multi vertical": "CSS Font & Text" -> text-align":
Die Textausrichtung unter "CSS Font & Text" -> text-align "left", "right" wird nicht angezeigt. Der Text ist immer "center".

**Comment by Scrounger** [comment]
in e9b32ab8189a5926137139c9e45cd0bc8335525d enthalten
