### ISSUE TITLE
Typo in den Einstellungen vom Line History Chart

### ISSUE THREAD

**Issue by Steff42** [Scrounger/ioBroker.vis-materialdesign#105]
In den Einstellungen des Line History Chart ist ein kleiner Typo beim Zeitintervall. Es steht dort 10 Minutesutes das soll wohl 10 Minuten heißen. Installiert ist bei mir die Version 0.3.19.

Siehe Screenshot:
![image](https://user-images.githubusercontent.com/35137293/90336086-c5580a00-dfd9-11ea-8cf0-ade9a6c64f4e.png)

**Comment by Scrounger** [comment]
ist im vis dapter falsch, pr hab ich gemacht
https://github.com/ioBroker/ioBroker.vis/pull/294
