### ISSUE TITLE
Performanceprobleme IconList bei zu vielen Einträgen

### ISSUE THREAD

**Issue by Frank1604** [Scrounger/ioBroker.vis-materialdesign#107]
Ich benutze die Iconlist als Titelliste. Jedes Item hat den gleichen Datenpunkt. Durch setzen des aktuellen Titels auf diesem Datenpunkt wird immer immer genau ein Item active, die anderen inactive (der Wert passt ja nur zu einem Item).

Das Laden der Liste geht auch mit vielen Einträgen (ca. 100) relativ schnell, jedoch macht das setzten des Active-Status Probleme. Hier kann ich Verzögerungen bis zu 1ner Minute feststellen in denen die Vis komplett einfriert.

[Hier](https://forum.iobroker.net/post/489363) habe ich es etwas genauer beschrieben.

**Comment by Scrounger** [comment]
Performance hängt vom Endgerät ab, mit dem man die VIS anzeigen lässt. Was verwendest du hier?

Zur Analyse brauch ich bitte die json daten und das Widget als export.

**Comment by Frank1604** [comment]
Ich habe es auf mehreren Geräten getestet. Tablet ist klar etwas schwach aber hier am Entwicklungsrechner ist das Problem nicht besser, sowohl im Firefox 80 als auch im Chrome 85.

Hier die Daten.
Widget:
`[{"tpl":"tplVis-materialdesign-Icon-List","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","wrapItems":true,"vibrateOnMobilDevices":"5","listLayout":"standard","itemLayout":"horizontal","buttonLayout":"full","titleLayout":"headline6","autoLockAfter":"","lockIconTop":"5","lockIconLeft":"5","lockFilterGrayscale":"30","lockApplyOnlyOnImage":"true","listItemDataMethod":"jsonStringObject","countListItems":"0","listType0":"text","showValueLabel0":"true","listType1":"text","showValueLabel1":"true","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"json_string_oid":"datenpunkte.0.sonos.visplayer.titelliste","maxItemsperRow":"1","listType2":"text","showValueLabel2":"true","itemGaps":"1","listType3":"text","showValueLabel3":"true","listType4":"text","showValueLabel4":"true","itemBackgroundColor":"#535353","iconHeight":"30","labelFontColor":"#FFFFFF","iconItemMinWidth":"","listImage0":"music-note","labelFontSize":"15","subLabelFontSize":"13","subLabelFontColor":"#b5b5b5","cardUse":false,"verticalIconContainerHeight":"","horizontalIconContainerWidth":"50","buttonHeight":""},"style":{"left":"816px","top":"49px","z-index":"4","width":"461px","height":"453px","overflow-y":"scroll"},"widgetSet":"materialdesign"}]`
erzeugtes JSON:
[titlelist.json.txt](https://github.com/Scrounger/ioBroker.vis-materialdesign/files/5233233/titlelist.json.txt)


Wie gesagt, das Problem tritt nicht beim ersten Laden der Liste auf sondern dann, wenn sich der zugrundeliegende Datenpunkt ändert und somit ein anderes Item aktiv wird.

**Comment by Scrounger** [comment]
Ich kann das leider nicht reproduzieren.
Was steht in der browser console (F12) wenn das Problem auftritt?

Bitte teste mal ob das Problem auch auftritt mit dem VIS Adapter v1.2.9.

Ich habe einen Verdacht woran das vlt. liegen könnte.

**Comment by Frank1604** [comment]
Leider gibt die Entwicklerkonsole nichts her. Weder Firefox noch Chrome. Keine requests, keine Fehler, nichts. Es hängt einfach. Firefox hängt das Fenster komplett, Chrome meldet nach einer Weile, dass das Fenster hängt und ich darf entscheiden ob ich warten möchte oder lieber nicht.

Downgrade auf 1.2.9 habe ich durchgeführt, leider keine Veränderung.

**Comment by Frank1604** [comment]
Ich muss mich korrigieren, mit der 1.2.9 ist es noch deutlich langsamer geworden. Habe es gerade nochmal getestet.

**Comment by Scrounger** [comment]
Hab den Fehler jetzt reproduzieren können.
Problem ist das immer die gleiche objectId für jeden Eintrag verwändet wird. D.h. wenn du z.B. 100 Einträge hast, wird bei einer Änderung 100 mal das change event ausgeführt. Und im change event werden alle 100 Einträge durchlaufen und entsprechend geupdated - das erzeugt schon nen bissle last ;-)

Ich hab was eingebaut und sollte jetzt gehen. Bitte teste die aktuelle github version und gib ne Rückmeldung!

**Comment by Frank1604** [comment]
Ja, das ist schon ordentlich Last, da hast du Recht. Aber trotzdem ist das so für mich der optimale Weg, wenn es einen besseren gibt nur her damit. :)
Ich habe die Version von hier getestet und das Problem ist damit definitiv behoben! Vielen Dank, großartige Arbeit!

Du solltest soeben auch einen oder zwei Kaffee erhalten haben. ;)

btw. gibt es eigentlich einen Weg, zum jeweils aktiven Element der Liste zu scrollen, sprich den Focus darauf zu setzen?

**Comment by Scrounger** [comment]
> 
> 
> Ja, das ist schon ordentlich Last, da hast du Recht. Aber trotzdem ist das so für mich der optimale Weg, wenn es einen besseren gibt nur her damit. :)
> Ich habe die Version von hier getestet und das Problem ist damit definitiv behoben! Vielen Dank, großartige Arbeit!
> 
> Du solltest soeben auch einen oder zwei Kaffee erhalten haben. ;)

Da hab ich auch echt grübeln müssen, bis ich auf den Trichter gekommen. Top freut mich das es funktioniert.
Dann kann ich meine Playlist ja auch endlich mal machen ;-)
 
> btw. gibt es eigentlich einen Weg, zum jeweils aktiven Element der Liste zu scrollen, sprich den Focus darauf zu setzen?

Perfekt, das hab ich voll aus dem Kopf verloren, hab dazu ein Issue aufgemacht #108
