### ISSUE TITLE
[IconList]: Grafik statt Icon

### ISSUE THREAD

**Issue by Frank1604** [Scrounger/ioBroker.vis-materialdesign#109]
Es wäre schön, wenn man eine Grafik statt der festen Icons verwenden könnte, für mich wäre das ein deutlicher Mehrwert. Vielleicht ist das ja relativ einfach umzusetzen.

Konkreter Fall bei mir: Ich verwende die Iconliste als Titelliste und auch als Favoritenliste für meinen Sonos-Player. Hier würde ich gerne das Albumcover als Bild nehmen.

**Comment by Scrounger** [comment]
Geht doch schon, entweder über Button Grafik auswählen oder Pfad direkt eingeben.
Das geht auch per Jason.

**Comment by Frank1604** [comment]
Und ich hätte schwören können ich hätte genau das probiert.
Asche auf mein Haupt, es funktioniert natürlich bereits wiw von dir beschrieben.

![grafik](https://user-images.githubusercontent.com/10420590/94172668-125db480-fe93-11ea-81f0-24a44ba63654.png)

**Comment by Scrounger** [comment]
Das geht bei allen Widgets Icon oder Image. Außer ich hab es vergessen ;-)
