### ISSUE TITLE
TopAppBar leitet nicht in neue View weiter

### ISSUE THREAD

**Issue by Ahrenfelde** [Scrounger/ioBroker.vis-materialdesign#11]
Hallo,

das Widged TopApp Bar funktioniert bei mir nicht richtig.
Ich habe die Views angegeben und einen Datenpunkt zugeordet.
Der Datenpunkt ändert sich auch wenn ich die View wechseln möchte, aber die View wechselt nicht im Browser. Brauche ich ein zusätzliches Script, welches mir die Views wechselt?

Browser: Firefox
Adapter Version: 0.1.5
Vis: 1.2.2

Grüße
Jan

**Comment by Scrounger** [comment]
Bin mir ziemlich sicher das des kein Bug ist.

Wie sehen deine Einstellungen aus?
Bacuhe die Log der Console zur Laufzeit?
Welche Firefox version?

**Comment by mark77-DE** [comment]
Hi Scrounger,

gleiche Problem bei mir.

Firefox: 70.0.1

`
10:13:24.940 Version vis-canvas-gauges: 0.1.5 index.html:4053:25
10:13:24.995 Version vis-colorpicker: 1.0.1 index.html:4593:13
10:13:25.032 Version vis-history: 1.0.0 index.html:6125:25
10:13:27.232 Version Info-Adapter-Widget: 0.0.9 info.js:22:21
10:13:27.317 Version vis-jqui-mfd: 1.0.12 index.html:7183:21
10:13:27.408 Version justgage: 1.0.2 justgage.js:115:21
10:13:27.516 Version iobroker.vis-keyboard: 0.0.2 keyboard.js:25:21
10:13:27.526 Version kodi: 0.2.2 kodi.js:47:21
10:13:27.534 Version lcars: 1.0.4 index.html:11723:25
10:13:27.541 Version vis-map: 1.0.0 index.html:12453:25
10:13:27.557 Version material: 0.1.3 material.js:29:21
10:13:27.826 Version vis-materialdesign: 0.1.5 materialdesign.js:25:21
10:13:27.891 Metro version: "1.1.2" index.html:14526:10
10:13:27.906 Version players: 0.1.0 players.js:58:21
10:13:27.920 Version vis-plumb: 1.0.0 index.html:16048:25
10:13:27.945 unreachable code after return statement
RGraph.common.effects.js:183:8
10:13:28.081 Version squeezeboxrpc: 0.6.0 squeezeboxrpc.js:65:21
10:13:28.240 Version vis-weather: 2.3.2 index.html:22303:25
10:13:28.242 Version vis-canvas-gauges: 1.0.5 index.html:23308:25
10:13:30.037 2019-11-18T09:13:30.037Z Connected => authenticate conn.js:273:25
10:13:31.410 2019-11-18T09:13:31.411Z Authenticated: true conn.js:293:33
10:13:31.420 Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://iobroker-ip:8082/vis/widgets/materialdesign/css/material-components-web.min.css
Source-Map-Adresse: material-components-web.min.css.map

10:13:31.574 Request 0 states. vis.js:3313:33
10:14:25.478 Destroy 200_Tools vis.js:2614:17
`

Ich benutze eine leere Seite, nur mit dem einen Widget.
Man kann das Menü öffnen, es sind alle Einträge zu sehen, auch Untermenüs funktionieren.
Es wird jedoch keine Seite geladen, im Log erscheinen keine weiteren Einträge.

Benötigst du mehr Infos?

**Comment by Scrounger** [comment]
Testet bitte zunächst Mal mit dem aktuellen master Branch.
Wichtig ist das ein Datenpunkt von Typ Zahl der tooappbar zugewiesen ist, sonst funktioniert das auch nicht.

Am besten neben der console Log Screenshot von allen Einstellungen machen, das Widget exportieren und hier posten

**Comment by mark77-DE** [comment]
Moin, habe jetzt mit 0.1.5 getestet, leider auch keine Funktion.

Firefox Log, nach dem Laden gibt es keine weiteren Logeinträge:
![FirefoxLog](https://user-images.githubusercontent.com/31760710/69127082-dce57f00-0aa9-11ea-855d-f5febda8289e.png)



Das Widget:
`[{"tpl":"tplVis-materialdesign-Drawer","data":{"oid":"nothing_selected","g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","count":"1","topAppBarLayout":"standard","titleTopAppBar":"Material Design Widgets","vibrateTopAppBarOnMobilDevices":"50","drawerLayout":"modal","drawerItemLayout":"standard","listItemDividerStyle":"standard","showHeader":"true","headerLabel":"<h4 class='mdc-drawer__title'>Material Design Widgets</h4><h6 class='mdc-drawer__subtitle'>by Scrounger</h6>","showLabels":"true","backdropLabelBackgroundHeight":"30","vibrateDrawerOnMobilDevices":"0","drawerSubItemLayout":"standard","showSubItemsLabels":"true","iconDrawer0":"/vis/widgets/materialdesign/img/IoBroker_Logo.png","iconDrawer1":"/vis/widgets/materialdesign/img/IoBroker_Logo.png","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"contains_view_0":"test","topAppBarZ_index":"1","contains_view_1":"test"},"style":{"left":"161px","top":"104px"},"widgetSet":"materialdesign"}]`


Brauchst du Screenshots von allen Einstellungen? Ich habe alles auf "Default" gelassen, außer "View für Tab"
![vis-materialdesign_0-1-5](https://user-images.githubusercontent.com/31760710/69126824-5c268300-0aa9-11ea-9ff3-dde8b067dc26.png)

**Comment by sigi2345** [comment]
https://forum.iobroker.net/topic/26199/test-adapter-material-design-widgets-v0-1-x/139

**Comment by mark77-DE** [comment]
Es geht, ich habe das Widget falsch verstanden.
Ich dachte das über das Widget, neue Seiten geladen werden und nicht, dass die Seiten innerhalb des Widgets dargestellt werden!!!

Tut mir Leid für die Unannehmlichkeiten
