### ISSUE TITLE
[IconList]: Mehrere Iconlists beeinflussen sich gegenseitig

### ISSUE THREAD

**Issue by Frank1604** [Scrounger/ioBroker.vis-materialdesign#110]
Gibt es mehrere Iconlists in einer View, so beeinflussen sie sich gegenseitig.

Einfaches Beispiel: Die Eigenschaft Bildhöhe, beeinflusst bereits im Editor beide Listen.
Weiteres Beispiel: 2 Listen mit unterschiedlichen Datenpunkten. Klick auf einen Datenpunkt in Liste 1 lässt einen anderen Datenpunkt in Liste 2 aktiv werden.

Es scheint der jQuery Selektor zu gierig zu sein und beide Listen anzusprechen

**Comment by Scrounger** [comment]
Welche Version hast?

**Comment by Frank1604** [comment]
Die hier von Github, die mit der Änderung das auch 100 Listenelemente keine Performanceprobleme mehr machen ;)

**Comment by Scrounger** [comment]
Dann installier Mal die aktuelle von GitHub, da müsste das schon gelöst sein

**Comment by Frank1604** [comment]
Mit der aktuellen Version von hier funktioniert es, vielen Dank! :)
