### ISSUE TITLE
Material Design Widget "materialdesign - Input": Is it possible to add attribute „autofocus“?

### ISSUE THREAD

**Issue by ice987987** [Scrounger/ioBroker.vis-materialdesign#113]
Material Design Widget "materialdesign - Input": Is it possible to add attribute „autofocus“?

like: https://wiki.selfhtml.org/wiki/Referenz:HTML/Attribute/autofocus

**Comment by Scrounger** [comment]
i use the vuetify api. seems there is an option for autofocus.
https://vuetifyjs.com/en/api/v-text-field/#props

will give it a try

**Comment by ice987987** [comment]
That would be great. Maybe this command can also be implemented in the „materialdesign  autocomplete“ widget.
