### ISSUE TITLE
Top-App-Bar-Navigation Problem

### ISSUE THREAD

**Issue by aldoa1** [Scrounger/ioBroker.vis-materialdesign#115]
Die Top-App-Bar-Navigation macht bei mir Probleme.
Öffne ich die index Seite zuckt ganz kurz der erste View (mein Startview) und dann sehe ich nur noch die Top-App-Bar und eine weisse Seite.
Wenn ich dann im Menü die erste Seite auswähle, ist die Darstellung so wie ich es von Anfang an benötige.

Was könnte das Problem sein?

**Comment by Scrounger** [comment]
Brauche das consolen log.
Und am besten ein Video von dem Verhalten.
Welche Version verwendest du?
