### ISSUE TITLE
Material Design Widget "materialdesign - autocomplete": bei erneuten Klick -> alles markiert

### ISSUE THREAD

**Issue by ice987987** [Scrounger/ioBroker.vis-materialdesign#117]
Eine weitere Frage zum Widget „materialdesign - autocomplete“:
Wenn bereits eine Eingabe vorhanden ist, weggeklickt und wider ins Inputfeld reingeklickt wird (oder die Seite neu geladen wird), ist automatisch die ganze Eingabe markiert und es muss ein weiteres Mal reingeklickt werden um die Eingabe vervollständigen zu können. Gibt's einen Workaround um die komplette Markierung zu umgehen? Die komplette Markierung benötige ich ja nicht/nie, da ich ja die Option „Textfeld löschen“ aktivieren kann.

![1601877219934-10a336dd-da18-4b36-a825-8215e573c035](https://user-images.githubusercontent.com/69053781/97103679-4274bf00-16ae-11eb-8ea9-1241ea931f40.jpeg)

**Comment by Scrounger** [comment]
mit welchem Browser tritt das auf?

**Comment by ice987987** [comment]
google chrome (87.0.4280.66 64-Bit WIN) und iOS14.2 Safari

**Comment by Scrounger** [comment]
diese option gibt es nicht in der vuetify api, von daher kann ich da leider auch nichts ändern.
Kann man aber sicher verbiegen per css. Für den Adapter werd ich das nicht umsetzen, da ich die APIs nicht zu arg verbiegen möchte.
