### ISSUE TITLE
[Table Widget] Flickers on change using Binding

### ISSUE THREAD

**Issue by kridh** [Scrounger/ioBroker.vis-materialdesign#119]
My Problem: when a table cell contains a  data binding object, eg a simple numeric value {0_userdata.0.test1}  and test1 changes (by an external event) : the table flickers !

To demonstrate this effect I've created a simple table example with a slider in one cell and the data-object in another cell. The data object referred to is created manually in the  iobroker-admin interface.

When I move the slider with my mouse the table flickers after release of the mouse button. I can also observe that for a very short moment the slider is shown in the wrong position  ( zero?).

The materialdesign list-widget does not show this behaviour.

Is this a feature of the table or can the issue resolved in the near future?

adapter version used is: 0.3.19

widget export:
[{"tpl":"tplVis-materialdesign-Table","data":{"oid":"nothing_selected","g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","countCols":"0","tableLayout":"standard","showHeader":"true","headerTextSize":"headline6","showColumn0":"true","colType0":"text","textAlign0":"center","showColumn1":"true","colType1":"text","textAlign1":"center","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"dataJson":"[\n    { \n        \"slider\":{\n                \t\"type\": \"slider\",\n                \t\"width\": \"187px\",\n                \t\"height\": \"60px\",\n                \t\"oid\": \"0_userdata.0.test1\",\n                \t\"orientation\": \"horizontal\",\n                \t\"knobSize\": \"knobSmall\",\n                \t\"step\": \"1\",\n                \t\"vibrateOnMobilDevices\": \"50\",\n                \t\"showTicks\": \"no\",\n                \t\"showValueLabel\": \"true\",\n                \t\"valueLabelWidth\": \"50\",\n                \t\"showThumbLabel\": \"no\",\n                \t\"valueLabelUnit\": \"%\",\n                \t\"prepandTextWidth\": \"1\"\n                }\n        \n    },\n    {\n       \"myValue\": \"{0_userdata.0.test1}\"\n    }\n  ]","colorBackground":"lightgrey","colorHeaderRowBackground":"grey","colorHeaderRowText":"yellow"},"style":{"left":"258px","top":"421px","width":"212px","height":"250px"},"widgetSet":"materialdesign"}]

**Comment by Scrounger** [comment]
I know this issue. Unfortunately, I can't fix it with the widget, because this is caused by the way the binding works. If a value that is used as a binding in a widget changes, the whole widget is recreated.
But because the table widget is created at runtime, among other things because of the function to use other widgets in the table, this phenomenon occurs.

There are two possible solutions.

1. [Use the html control object](https://github.com/Scrounger/ioBroker.vis-materialdesign#html):
```
[
	{
		"col1": {
			"type": "html",
			"oid": "0_userdata.0.table_binding_flickr",
			"html": "[#value]"
		}
	}
]
```

2. Create the json with a javascript. Implement a listener that changes the value of the json.
