### ISSUE TITLE
[Slider Widget] Fehlende Beschriftung, wenn umgekehrt

### ISSUE THREAD

**Issue by frank2604** [Scrounger/ioBroker.vis-materialdesign#121]
Hallo,

kannst Du mal schauen: Wenn man die Slider-Richtung umkehrt, geht die Beschriftung der Schritte nicht mehr.

![1604517943691-2020-11-04_20-19-11](https://user-images.githubusercontent.com/51050855/99909662-2df60780-2cea-11eb-9310-356dc930f15d.jpg)

Danke

Frank

**Comment by Scrounger** [comment]
bereits in 0.4.0 behoben
