### ISSUE TITLE
Can't see my existing Text input fields..

### ISSUE THREAD

**Issue by itProfi** [Scrounger/ioBroker.vis-materialdesign#126]
After this commit  https://github.com/Scrounger/ioBroker.vis-materialdesign/tree/3499a3ef6b79b630352f968275f114b60ad3e756 i can't see my existing input fileds..(
![Скриншот 11-12-2020 145509](https://user-images.githubusercontent.com/6728198/101900891-4490cf80-3bc1-11eb-9ff2-74e18dc6a295.jpg)

**Comment by Scrounger** [comment]
Please provide more informations. 
At the screenshot i can see the input field. Need the broswer log at runtime.

**Comment by itProfi** [comment]
Ok. Before update
![Скриншот 12-12-2020 133033](https://user-images.githubusercontent.com/6728198/101981526-aebb7a00-3c7e-11eb-821b-0b23deea04b1.jpg)
![Скриншот 12-12-2020 133030](https://user-images.githubusercontent.com/6728198/101981527-afeca700-3c7e-11eb-8100-7e483fe44919.jpg)
![Скриншот 12-12-2020 133024](https://user-images.githubusercontent.com/6728198/101981528-afeca700-3c7e-11eb-9883-c4e330d0242c.jpg)
After update:
![Скриншот 12-12-2020 133310](https://user-images.githubusercontent.com/6728198/101981534-bbd86900-3c7e-11eb-9ea7-120b211e1ae9.jpg)
![Скриншот 12-12-2020 133314](https://user-images.githubusercontent.com/6728198/101981537-bd099600-3c7e-11eb-90e9-05d785d497a3.jpg)

**Comment by itProfi** [comment]
After update:
![Скриншот 12-12-2020 133723](https://user-images.githubusercontent.com/6728198/101981600-37d2b100-3c7f-11eb-9edd-79f81f5713cc.jpg)
[192.168.1.100-1607769370389.log](https://github.com/Scrounger/ioBroker.vis-materialdesign/files/5682895/192.168.1.100-1607769370389.log)

**Comment by itProfi** [comment]
My fault! Always need restart web instance!
