### ISSUE TITLE
Fehler bei der Installation

### ISSUE THREAD

**Issue by Andyexe** [Scrounger/ioBroker.vis-materialdesign#128]
Hallo,

ich an das materialdesign nicht mehr in ioBroker installiert?
Ich bekomme immer eine Fehlermeldung auch, wenn ich über die Konsole installiert möchte.

npm WARN saveError ENOENT: no such file or directory, open '/home/andreas/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/andreas/package.json'
npm WARN andreas No description
npm WARN andreas No repository field.
npm WARN andreas No README data
npm WARN andreas No license field.

+ iobroker.vis-materialdesign@0.3.19
added 1 package from 1 contributor and audited 7 packages in 1.977s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

Grüße
Andy

**Comment by Scrounger** [comment]
Das ist kein Fehler des Adapters.
