### ISSUE TITLE
[Select] Datenpunkt wird unaufhörlich aktualisiert

### ISSUE THREAD

**Issue by BobBruni** [Scrounger/ioBroker.vis-materialdesign#13]
Enthält die OID einen Working Datenpunkt, so wird er selektierte Wert im Sekundentakt unaufhörlich neu gesendet.

Version: 0.2.x

**Comment by BobBruni** [comment]
Gleiches Problem bei einem Datenpunkt (Zahl) ohne Working Datenpunkt.

**Comment by Scrounger** [comment]
fixed in 159c3dc
