### ISSUE TITLE
Erweiterungswunsch - OID in Progressbar für Farben Fortschritt

### ISSUE THREAD

**Issue by CKMartens** [Scrounger/ioBroker.vis-materialdesign#131]
Wenn es möglich wäre, bitte die Möglichkeit einrichten bei den Bedingungen für den Farbe der Fortschritte in der Progressbar eine OID anzugeben (s. Bild)

![image](https://user-images.githubusercontent.com/19702758/102868753-df4ba280-443a-11eb-82c5-c338ba5c278e.png)

**Comment by Scrounger** [comment]
in 04fb96c9e741fcec92784a86399b248542b3c981 enthalten

**Comment by CKMartens** [comment]
Leider nicht, ich kann zwar die Farben als Datenpunkt angeben, aber nicht den Wert für die Bedingung.

![image](https://user-images.githubusercontent.com/19702758/102904827-8ef03700-4472-11eb-90ca-501cca640b52.png)
