### ISSUE TITLE
Warum nicht im latest?

### ISSUE THREAD

**Issue by Omega236** [Scrounger/ioBroker.vis-materialdesign#133]
Bei der Installation bei einem Kumpel ist mir aufgefallen dass dein Adapter nicht im latest ist.

Das ist echt schade da er das beste Paket für VIS ist und nicht für die meisten unbemerkt bleiben sollte.

**Comment by Scrounger** [comment]
hab bewusst vorab ne beta phase gemacht, da die Änderungen sehr groß waren.
siehe https://forum.iobroker.net/topic/39522/test-adapter-material-design-widgets-v0-4-0-beta
