### ISSUE TITLE
Dialog öffnet sich nicht auf einem Smartphone/Tablet

### ISSUE THREAD

**Issue by hdering** [Scrounger/ioBroker.vis-materialdesign#134]
Hallo,

ich habe ein Dialog eingebaut, welcher sich auf meinem PC im Chrome problemlos öffnet.
Versuche ich das auf meinem Smartphone im Chrome oder auf meinen Tablets passiert leider nichts.
In Chrome als auch über den Fully Kiosk Browser öffnet sich nichts.
Ein "metro - Tile Dialog" wird hingegen problemlos angezeigt.

Sollte das grundsätzlich funktionieren?

Eigentlich ist es ein Standard "materialdesign - dialog". Hier der Export des widgets:

`[{"tpl":"tplVis-materialdesign-Vuetify-Dialog-View","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","showDialogMethod":"button","fullscreenResolutionLower":"100","vibrateOnMobilDevices":"50","buttonStyle":"icon","mdwButtonPrimaryColor":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.button.default.primary;dark:vis-materialdesign.0.colors.dark.button.default.primary; mode === \"true\" ? dark : light}","mdwButtonSecondaryColor":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.button.default.secondary;dark:vis-materialdesign.0.colors.dark.button.default.secondary; mode === \"true\" ? dark : light}","textFontFamily":"{vis-materialdesign.0.fonts.button.default.text}","textFontSize":"{vis-materialdesign.0.fontSizes.button.default.text}","iconPosition":"left","closingClickOutside":"true","showTitle":true,"titleFontSize":"{vis-materialdesign.0.fontSizes.dialog.title}","titleFont":"{vis-materialdesign.0.fonts.dialog.title}","titleColor":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.dialog.header_text;dark:vis-materialdesign.0.colors.dark.dialog.header_text; mode === \"true\" ? dark : light}","buttonPosition":"flex-end","buttonSize":"medium","buttonFont":"{vis-materialdesign.0.fonts.dialog.button}","buttonFontColor":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.dialog.close_button_text;dark:vis-materialdesign.0.colors.dark.dialog.close_button_text; mode === \"true\" ? dark : light}","fullscreenCloseIcon":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.dialog.close_button_icon;dark:vis-materialdesign.0.colors.dark.dialog.close_button_icon; mode === \"true\" ? dark : light}","pressColor":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.dialog.close_button_press;dark:vis-materialdesign.0.colors.dark.dialog.close_button_press; mode === \"true\" ? dark : light}","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"contains_view":"View_Camera","showDialogOid":"","dialogMaxWidth":"600","viewHeight":"550","backgroundColor":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.dialog.background;dark:vis-materialdesign.0.colors.dark.dialog.background; mode === \"true\" ? dark : light}","showDivider":false,"buttontext":"","image":"/icons-mfd-png/it_camera.png","iconHeight":"108","viewDistanceToBorder":"","headerHeight":"","footerHeight":"","headerBackgroundColor":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.dialog.header_background;dark:vis-materialdesign.0.colors.dark.dialog.header_background; mode === \"true\" ? dark : light}","footerBackgroundColor":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.dialog.footer_background;dark:vis-materialdesign.0.colors.dark.dialog.footer_background; mode === \"true\" ? dark : light}","fullscreenCloseIconColor":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.dialog.close_button_icon;dark:vis-materialdesign.0.colors.dark.dialog.close_button_icon; mode === \"true\" ? dark : light}","dividerColor":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.dialog.divider;dark:vis-materialdesign.0.colors.dark.dialog.divider; mode === \"true\" ? dark : light}","overlayColor":"{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.dialog.overlay;dark:vis-materialdesign.0.colors.dark.dialog.overlay; mode === \"true\" ? dark : light}","buttonFontSize":"{vis-materialdesign.0.fontSizes.dialog.button}"},"style":{"left":"486px","top":"709px","width":"103px","height":"102px"},"widgetSet":"materialdesign"}]`

**Comment by fireboyff** [comment]
Der Dialog öffnet sich auch bei State Änderung nicht.
Mein State wird via Blockly Aktualisiert, hier reagiert er nur wenn ich True als String reinschreibe obwohl der State Typ Boolen ist. Jedoch reagiert dann der Dialog.

Alternativ funktioniert es auch wenn ich dem State zusätzlich mit einen Button Linke, dann reagiert er auch.

**Comment by Scrounger** [comment]
![grafik](https://user-images.githubusercontent.com/6370451/106361966-7fd99000-6320-11eb-8f23-e9caa1a0dd23.png)

method to show dialog steht auf `button`, muss aber auf `datapoint` gesetzt werden wenn man einen Datenpunkt verwenden möchte.
