### ISSUE TITLE
[Select] No theme is not applied to Select 'color of inner prefixed symbol'

### ISSUE THREAD

**Issue by cdellasanta** [Scrounger/ioBroker.vis-materialdesign#137]
**Describe the bug**  
Applying theme configuration to existing `tplVis-materialdesign-Select` widget ("use theme" button) the  `color of inner pixelfield symbol` remains `#ffffff` .. while `text color` changes to `{mode:vis-materialdesign.0.colors.darkTheme;light:vis-materialdesign.0.colors.light.input.text;dark:vis-materialdesign.0.colors.dark.input.text; mode === "true" ? dark : light}` 

_(in addition, but out of scope here, the default light color for `input.text`should not be white?)_

**Expected behavior**  
Variable value should be set depending on `mode:vis-materialdesign.0.colors.darkTheme`

Current workaround, set to `{mode:vis-materialdesign.0.colors.darkTheme; mode === "true" ? "#303030" : "#ffffff" }`

**Versions:**  
 - Adapter version: 0.4.1
 - JS-Controller version: 4.1.12
 - Node version: v12.18.4 
 - Operating system: linux (Raspbian)

**Comment by Scrounger** [comment]
What do you mean with `inner pixelfield symbol`?
Please provide a screenshot of the field.

**Comment by cdellasanta** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/70055566/103439905-63730680-4c41-11eb-9db7-5053a023a308.png)

**Comment by Scrounger** [comment]
I have deliberately not predefined themes for the icons (prefix, inner prefix, append, outer append). Because my experience shows that I design them differently for each widget, especially the color.

For the select there are only themes for the close and collapse icon.
My understanding is that this is not a mistake?

**Comment by cdellasanta** [comment]
No, it is not a real issue .. 

It's only one of the few things I had to adapt manually after applying the theme for all Select I have in views .. 

If it's the desired behaviour, is ok for me.
