### ISSUE TITLE
Werteliste beim Autocomplete und Select Widget funktioniert nicht

### ISSUE THREAD

**Issue by Gitpaad** [Scrounger/ioBroker.vis-materialdesign#138]
Hellohello

Bei mir funktioniert die Werteliste beim Autocomplete und Select Widget nicht.
Gemäss Anleitung müssen die Werte jeweils mit einem Koma getrennt werden. Sollte eigentlich gehen..

Es kommt dann aber nur eine Zeile mit allen Werten aneinander.

Kannst du das mal prüfen? vielleicht stimmt auch bei mir was nicht..

lg Pad

**Comment by Scrounger** [comment]
Trennzeichen ist Strichpunkt.
Da war die Doku noch nicht aktuell - habs aktualisiert.
