### ISSUE TITLE
Runde Ecken beim HTML Card

### ISSUE THREAD

**Issue by Gitpaad** [Scrounger/ioBroker.vis-materialdesign#139]
Hellohello

Könnte man bei der HTML Card die Ecken ohne Rundung machen? Im Darkmodus in kombination mit einer Grid View gibt es dann so unschöne weisse Punkte ganz ausen in den Ecken im Grid. siehe Foto:

![2021-01-04 02_16_36-vis - Firefox Nightly](https://user-images.githubusercontent.com/66991726/103493786-9ed52700-4e33-11eb-86f7-0854ce1c5dbe.png)

Das wäre super ;)

Lg

**Comment by Scrounger** [comment]
Du musst die Hintergrundfarbe der view, in der sich das Card Widget befindet anpassen - am besten auf `transparent`
