### ISSUE TITLE
Automatischer Zeilenumbruch

### ISSUE THREAD

**Issue by BobBruni** [Scrounger/ioBroker.vis-materialdesign#14]
Automatischer Zeilenumbruch beim erreichen der maximalen Widgetbreite.

![image](https://user-images.githubusercontent.com/58072812/69421060-5f777400-0d20-11ea-8ff7-afbbe678420d.png)

**Comment by Scrounger** [comment]
Welches Widget betrifft das nochmal, find den post nicht mehr.

**Comment by BobBruni** [comment]
Ursprünglich ging es um das List- und um das HTML-Card-Widget. Besten Dank!

**Comment by Scrounger** [comment]
Zeilenumbruch option für table in 0ffc40a093d4160662285c87d6e1d39d27afca6f

**Comment by Scrounger** [comment]
@BobBruni 
Bei der HTML-Card geht das:

![geht](https://user-images.githubusercontent.com/6370451/69501685-a4a9ca80-0f07-11ea-8950-0d9249e6f308.gif)
