### ISSUE TITLE
Objekt-Browser öffnet sich nicht

### ISSUE THREAD

**Issue by dsiggi** [Scrounger/ioBroker.vis-materialdesign#140]
**Describe the bug**  
Der Objekt-Browser lässt sich nicht öffnen. Weder über den Menüpunkt "Setup -> Objekt-Browser" noch über die "Buch-Tasten" bei Objekt-ID-Feldern. Das Problem tritt nur auf wenn ich meine Visualisierung die ich mit ioBroker.vis-materialdesign erstellt habe lade. Lade ich die main-Vis welche bei ioBroker als Beispiel dabei ist, lässt sich der Objekt-Browser öffnen.

**To Reproduce**  
1. Öffnen des Projekts "Setup -> Projekt -> MaterialDesignVis"
2. Öffnen des Objekt-Browsers "Setup -> Objekt-Browser"
3. Sie Beschreibung oben bzw. Log.

**Expected behavior**  
Der Objekt-Browser sollte öffnen

**Screenshots & Logfiles** 
Folgende Meldung erscheint in der Konsole beim Klick

>Uncaught TypeError: e.get(...) is undefined
    s widgets.min.js:5
    n widgets.min.js:5
    vue widgets.min.js:6
    jQuery 7
    initTreeDialog selectID.js:2858
    show selectID.js:3541
    selectId selectID.js:3921
    editInitMenu visEdit.js:1628
    jQuery 2
    sentryWrapped helpers.ts:124
    Ht breadcrumbs.ts:80
    lt supports.ts:83
    jQuery 6
    editInitMenu visEdit.js:1588
    editInit visEdit.js:293
    afterInit vis.js:3335
    getConfig conn.js:1266
    onack socket.io.js:8
    onpacket socket.io.js:8
    exports socket.io.js:8
    emit socket.io.js:6
    ondecoded socket.io.js:6
    exports socket.io.js:8
    emit socket.io.js:6
    add socket.io.js:6
    ondata socket.io.js:6
    exports socket.io.js:8
    emit socket.io.js:6
    onPacket socket.io.js:7
    setTransport socket.io.js:7
    emit socket.io.js:6
    onPacket socket.io.js:7
    onData socket.io.js:7
    onmessage socket.io.js:8
    addEventListeners socket.io.js:8
    doOpen socket.io.js:8
    open socket.io.js:7
    probe socket.io.js:7
    onOpen socket.io.js:7
    onHandshake socket.io.js:7
    onPacket socket.io.js:7
    setTransport socket.io.js:7
    emit socket.io.js:6
    onPacket socket.io.js:7
    n socket.io.js:7
    decodePayload socket.io.js:7
    onData socket.io.js:7
    doPoll socket.io.js:7
    emit socket.io.js:6
    onData socket.io.js:7
    onLoad socket.io.js:7
    onreadystatechange socket.io.js:7
    create socket.io.js:7
    i socket.io.js:7
    request socket.io.js:7
    doPoll socket.io.js:7
    poll socket.io.js:7
    doOpen socket.io.js:7
    open socket.io.js:7
    open socket.io.js:7
    r socket.io.js:6
    r socket.io.js:6
    connect socket.io.js:6
    r socket.io.js:6
    r socket.io.js:6
    r socket.io.js:6
    init conn.js:240
    main vis.js:3377
    <anonymous> vis.js:3650
    jQuery 11
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://server:8082/lib/js/socket.io.js
Source-Map-Adresse: socket.io.js.map

**Versions:**  
 - Adapter version: 0.4.2
 - JS-Controller version: 3.1.6 
 - Node version: v12.20.0 
 - Operating system: Docker Image von buanet [Docker Hub](https://hub.docker.com/r/buanet/iobroker)

**Comment by Scrounger** [comment]
Welchen Browser verwendest du?
Hast du mal dein System neugestartet, weil der Fehler sollte eigentlich behoben sein seit 0.4.1?

**Comment by dsiggi** [comment]
Hi,
ich verwende den Firefox, wenn ich später zu hause bin werde ich auch mal einen anderen Browser testen.
Ich habe das Dockerimage schon mehrmals gestoppt und wieder gestartet. Hat leider nichts gebracht.

**Comment by Scrounger** [comment]
Welche VIS Adapter Version ist installiert? Muss >= 1.3.6 sein

**Comment by dsiggi** [comment]
Ich nutze 1.3.4. Selbst wenn ich das Verwahrungsort auf "Beta (latest)" umstelle ist die neuste Version 1.3.4.
Ich habe mir daher die 1.3.6 mal über GitHub gezogen und jetzt funktioniert der Objekt-Browser wieder.
Danke für deine Hilfe.
