### ISSUE TITLE
Support für ioBroker.vis-keyboard?

### ISSUE THREAD

**Issue by dsiggi** [Scrounger/ioBroker.vis-materialdesign#141]
Hi,
ist es möglich das Tastaturwidget zusammen mit dem materialdesign zu nutzen?
Ich hab das Widget an folgenden Stellen eingefügt:

- Auf der Seite mit der AppBar
- Auf dem view mit dem Masonry-Widget
- Auf der Card die im Masonry-Widget angezeigt wird

Leider hat nichts davon funktioniert. Die Tastatur wird nicht angezeigt.

**Comment by Scrounger** [comment]
Geteste ob es in einer leeren view überhaupt funktioniert?
Bei mir geht es nicht, ist ein Problem des ioBroker.vis-keyboard adapter. Mach dort ein Issue auf.
