### ISSUE TITLE
Material Design Widget: Progress Widget: Farben zu Werten werden nicht angezeigt

### ISSUE THREAD

**Issue by happyuser20** [Scrounger/ioBroker.vis-materialdesign#143]
Möchte den Kreis als Anzeige für den aktuellen Stromverbrauch nutzen.

Den Wechsel von zwei Farben bekomme ich hin aber die dritte nicht!

Es soll so aussehen
-500 W bis 0 W grün (wenn meine Mini-PV mehr liefert als ich verbrauche.
0 W bis ca. 3000 W gelb
alles über 3000 W rot

Scheint ein Bug zu sein, funktioniert nur wenn man Prozent und nicht Wert verwendet.

**Comment by Scrounger** [comment]
Werte müssen in Prozent angeben werden.
Mehr dazu siehe https://forum.iobroker.net/topic/33623/material-design-widgets-progress-widget/18

Muss mit in die Doku aufgenommen werden
