### ISSUE TITLE
IconList: Bei Verwendung von "buttonNav" werden nicht alle Listenelemente aus dem json geladen

### ISSUE THREAD

**Issue by m50434** [Scrounger/ioBroker.vis-materialdesign#145]
Ich benutze die IconList, um mir den Status alle Fenster anzeigen zu lassen (auf/zu) sowie die Temperatur.

Wenn ich die einzelnen Einträge mit dem listType "text" oder "ButtonState" anzeigen lasse, dann werden unmittelbar, wenn ich die View neu lade, alle Listeneinträge korrekt angezeigt.

Benutze ich hingegen als listType "ButtonNav" (oder z.B. auch "ButtonLink") (ich wollte die Thermoste-View hinter den Icons verlinken), so wird mir nur ein Element in der Liste angezeigt, sobald ich die View neu lade.
Starte ich das Script, dass das JSON mit den ganzen Fenstereinträgen erzeugt, neu und lade die View nicht neu, so werden mir mal alle, mal fast alle Listenelemente angezeigt. Das ist doch sehr komisch.

Woran könnte das liegen, dass beim Neuladen der View nur ein Eintrag angezeigt wird (obwohl das JSON-Objekt vollständig ist) und es vor allem bei listType "Text" sofort alles lädt?

**Comment by Scrounger** [comment]
folgendes wird benötigt:
* json string
* export deines widgets
* consolen log zur runtime (F12)

**Comment by m50434** [comment]
Habe das Problem gefunden:
Ich hatte fälschlicherweise im JSON unter "objectId" immer die ID der Homematic-Geräte hinterlegt. Das hat ihn scheinbar dazu gebracht, die ListenElemente nicht anzuzeigen. Nachdem ich die objectID aus dem JSON entfernt habe, geht es nun!
