### ISSUE TITLE
Alerts widget JSON-Objekt Erweiterung

### ISSUE THREAD

**Issue by Kernal87** [Scrounger/ioBroker.vis-materialdesign#146]
Ich benutze das Alerts Widget zum Anzeigen von Meldungen der Hausautomation. Leider kann es vorkommen, dass über Nacht diverse Meldungen sich angestaut haben, welche alle manuell gelöscht werden müssen. 
Ich fände es daher gut wenn man das JSONObject mit einen Timestamp und einem Typ erweitern könnte. 
So kann man mit einen Script nach Einträgen die "älter als sind" filtern und Einträge eines bestimmten Typs ersetzen. 
Ich habe bereits im Javascript 

`
[
       {
		"text": "we have a new message",
		"backgroundColor": "",
		"borderColor": "darkred",
		"icon": "message-alert-outline",
		"iconColor": "darkred",
		"fontColor": "blue",
                "TimeStamp": "1611565632",
                "SourceType": "Heizung"
	}, {
		"text": "we have a new message",
		"backgroundColor": "#e6b0aa",
		"borderColor": "green",
		"icon": "/vis/img/bulb_on.png",
		"iconColor": "green",
		"fontColor": "gold",
                "TimeStamp": "1611569632",
                "SourceType": "Kaffemaschine"
	}, {
		"text": "we have a new message",
		"backgroundColor": "",
		"borderColor": "gold",
		"icon": "alert-outline",
		"iconColor": "gold",
		"fontColor": "",
                "TimeStamp": "1611565632",
                "SourceType": "Server"
	}
]
`
Ich habe das Probiert bereits im Javascript anzupassen: 

`  json.push(
        {
            text:  text,
            backgroundColor: backgroundColor,
            borderColor: borderColor,
            icon: icon,
            iconColor: iconColor,
            fontColor: fontColor,
            timest: TimeinMS
        }
    )`

Leider wird timest nicht in den Datenpunkt geschrieben.

**Comment by Scrounger** [comment]
das funktioniert auch. Du kannst das Objekt was du in den json string umwandelst um belibieg viele properties erweitern.
D.h. erzeuge hier props für einen timestamp. Nach dem kannst du dann per skript filtern.
