### ISSUE TITLE
Top App Bar - Views werden nicht angezeigt

### ISSUE THREAD

**Issue by CKMartens** [Scrounger/ioBroker.vis-materialdesign#148]
Ich habe in eine Top App Bar angelegt mit Untermenüs. Ab dem 3. Element wird das angewählter View kurz angezeigt und dann springt die Anzeige auf das View von Element [0]. Dieses Verhalten wurde bereits im [Forum ](https://forum.iobroker.net/post/553741) von (mit mir) drei Usern angesprochen. 

Einstellungen in der View in Widget 8:
![image](https://user-images.githubusercontent.com/19702758/107075810-ecee9900-67ea-11eb-85d1-b0c8cbe12aad.png)

Einstellungen in der App Bar:
![image](https://user-images.githubusercontent.com/19702758/107075908-0a236780-67eb-11eb-8bed-b773de98cc43.png)
![image](https://user-images.githubusercontent.com/19702758/107075920-0d1e5800-67eb-11eb-9d59-9aa438a9e709.png)
![image](https://user-images.githubusercontent.com/19702758/107075930-10b1df00-67eb-11eb-95c0-65e27a4f51ba.png)

Anzeige in der VIS:
![image](https://user-images.githubusercontent.com/19702758/107075945-18718380-67eb-11eb-82f2-3788c852bb22.png)

**Comment by Scrounger** [comment]
Bitte das template für bug report verwenden und alle dort beschriebenen Angaben ausfüllen / bereitstellen, nur so kann ich evtl. helfen
