### ISSUE TITLE
Verbesserung des Line History Chart

### ISSUE THREAD

**Issue by Oliver6911** [Scrounger/ioBroker.vis-materialdesign#15]
Hallo es wäre schön, wenn du noch folgendes einbauen könntest:
1. Es sollte eine Möglichkeit geben nur das Diagrammfeld einzufärben.
2. Es sollte möglich sein die Messeinheit in der Y-Achse mit anzuzeigen.

Ein Beispiel aus Flot hänge ich mit an.
![Unbenannt](https://user-images.githubusercontent.com/58118806/69483680-95a11a80-0e2a-11ea-9f3a-4b7a0eb15387.JPG)

**Comment by Scrounger** [comment]
ist Implementiert in 90320510243df19aa8f26b087a60519470b3944f, fa325515265c5c7437f5db44fe41c5375439e0c0
