### ISSUE TITLE
[JSON Chart]: datalabel_override does not work

### ISSUE THREAD

**Issue by Kazuyakisho** [Scrounger/ioBroker.vis-materialdesign#152]
It seems that the datalabel override doesn't work in JSON Chart or I misunterstood that.

To reproduce, try overriding [line, bar]chart data labels with 
datalabel_override: array[string] (like in documentation)

What I wanted to try is replacing the datalabels (are for the correct calculation of points I guess) with own datalabels: As an example I want to have an empty string if datalabel equals '0'. 

```
 graphs.push(
    {
      data: sqlDurationSec.map(total => mapSecToDecSeconds(total)), <--- length = 7
      type: 'line',
      color: '#44739e',
      legendText: 'Gesamt',
      line_pointSizeHover: 5,
      line_pointSize: 3,
      line_Tension: 0.1,     
      yAxis_show: true,
      yAxis_gridLines_show: false,
      yAxis_gridLines_ticks_length: 5,
      yAxis_position: 'right',
      yAxis_appendix: ' h',
      yAxis_zeroLineWidth: 0.1,
      yAxis_zeroLineColor: 'black',
      yAxis_id: 0,
      yAxis_min: 0,
      yAxis_max: 15,
      yAxis_maxSteps: 10,
      barIsStacked: true,     
      displayOrder: 0,
      yAxis_title_text: 'Gesamtstunden',
      tooltip_AppendText: ' h',
      tooltip_MinDigits: 2,
      datalabel_backgroundColor: '',
      datalabel_color: '#44739e',
      datalabel_offset: -30,
      datalabel_fontFamily: 'RobotoCondensed-Medium',
      datalabel_fontSize: 10,
      datalabel_borderRadius: 6,
      datalabel_override: ['T','E','S','T','I','N','G'], <--- TEST with strings doesnt work 
      use_gradient_color: true,
      gradient_color: color_graph_all_verlauf,
      use_line_gradient_fill_color: true,
      line_gradient_fill_color: getGradientColors(5,20,color_graph_all_verlauf ).getGradientWithOpacity(40),
     }
```
If it works on your site, than maybe I have error in my code. 
KR

**Comment by Scrounger** [comment]
Please test the current github version, i made a bug fix

**Comment by Kazuyakisho** [comment]
Really good. Very fast and it works. 

Thank you very much. Top. :)

**Comment by Kazuyakisho** [comment]
Graphs:
![graphs](https://user-images.githubusercontent.com/5064026/110627090-d2b92980-81a1-11eb-93ac-75ab31bdda22.jpeg)

Console Log:
[console.log](https://github.com/Scrounger/ioBroker.vis-materialdesign/files/6115706/console.log)

After the error "Uncaught TypeError: Cannot read property 'call' of undefined in lib.min.js:4 comes up, the charts are no longer willing to update. That is happen while hovering over the overrided data labels. And after reload will F5 it is working normally.    See in Video:

here a little video - rename the file to error.webm
[error.zip](https://github.com/Scrounger/ioBroker.vis-materialdesign/files/6115716/error.zip)

JSON Strings:
[JSON Strings.txt](https://github.com/Scrounger/ioBroker.vis-materialdesign/files/6115776/JSON.Strings.txt)

**Comment by Scrounger** [comment]
Wie wäre es mit ner anderen Sprache ;-)

**Comment by Kazuyakisho** [comment]
Na dann machen wir dit so. :D  

Jap, Tooltip öffnet nicht. Und zudem interessant: Die Fehlermeldung kommt ÜBERALL wo ein Tooltip erwartet wird (CHART 1). Ich habe die Datalabels auch nur im LINE-Chart überschrieben und der Fehler wird überall geworfen, ob ich nun initial auf eine der BARS gehe oder auf LINE. 

CHART 2 (ohne datalabe_overrides). Reagiert dann ebenfalls nicht auf Updates aber schmeißt auch keine Fehler. 

Und vielleicht habe ich es auch vorher übersehen, aber hier kommt jetzt noch nen Array Error 
lib.min.js:4 Uncaught TypeError: Cannot read property 'length' of undefined
Hier nochmal die Log.
[error.log](https://github.com/Scrounger/ioBroker.vis-materialdesign/files/6117945/error.log)

**Comment by Scrounger** [comment]
Teste bitte die aktuelle version von github.
Upload vis adapter nicht vergessen.

**Comment by Kazuyakisho** [comment]
Hi. Jetzt musste ich erstmal nachschlagen, was du mit Upload VIS adapter meinst. oO

Habe VIS upgeloaded und die aktuelleste Version geladen, aber leider kein Erfolg oder ich mache irgendwas falsch.
Adapter -> GitHub -> vis-materialdesign auswählen ... dann wird dieses Kommando ausgeführt. ` ./iobroker url "https://github.com/Scrounger/ioBroker.vis-materialdesign/tarball/master" vis-materialdesign` Ist doch richtig oder?

![Screenshot from 2021-03-11 13-09-48](https://user-images.githubusercontent.com/5064026/110786088-02346880-826c-11eb-8c0c-be1ec80b73f3.png)

**Comment by Scrounger** [comment]
> Habe VIS upgeloaded und die aktuelleste Version geladen, aber leider kein Erfolg oder ich mache irgendwas falsch.
> Adapter -> GitHub -> vis-materialdesign auswählen ... dann wird dieses Kommando ausgeführt. ` ./iobroker url "https://github.com/Scrounger/ioBroker.vis-materialdesign/tarball/master" vis-materialdesign` Ist doch richtig oder?

Ja korrekt.
VIS upload geht so:
![upload](https://user-images.githubusercontent.com/6370451/110809728-77606780-8285-11eb-9083-9210b1212586.gif)

**Comment by Kazuyakisho** [comment]
Hääää. Nanu. Es läuft jetzt. 
Ich habe den debug modus erstmal ausgestellt und  TADA es geht. Wenn ich den Debug Modus jetzt wieder einschalte geht's auch. Top.

Aber überhaupt mal ein riesen Danke schön. Es ist echt schnike, was du da hingezimmert hast. :+1: :+1: :+1: 
Na dann gebe ich dir mal nen Kaffee aus ;)

**Comment by Kazuyakisho** [comment]
Jup. Läuft alles perfekt. Dann schließe ick mal das Ticket.
