### ISSUE TITLE
Slider, kleiner als Bedingung, größer als Bedingung => Text

### ISSUE THREAD

**Issue by sir0drake** [Scrounger/ioBroker.vis-materialdesign#154]
hallo,
es geht um den Slider und im speziellen darin die Werte die benannt sind mit:

min, max, schritte, kleiner als Bedingung, größer als Bedinung

bei min und max und die Schritte kann ich float-werte eingeben
zb   min = 7.5   max= 28.5   Schritte 0.5
bei "kleiner als Bedingung" und "größer als Bedingung" nur ganze Zahlen.

In der Ausführung des ganzen ( runtime ) wird der den Texten hinterlegten Werte auch angezeigt.
Aber nur bei exakt dem Wert der eingetragen wurde.

Erwartung:  wenn x <= Wert  dann Text
Aktuell:       wenn x    = Wert dann Text

ich kann x unterschreiten und dann ist der von mir gewünschte Text wieder weg.

viele Grüße

**Comment by Scrounger** [comment]
Bitte stell einen export deines Widget zur Verfügung

**Comment by sir0drake** [comment]
Hallo Scrounger,

leider habe ich heute beim versuch den Fehler nachzustellen eine leicht andere Ausprägung in der Anzeige.

ich habe die "kleiner als" und "größer als" Bedingung weiter weg gesetzt von den min und max werten.
jetzt ist es so, das der entsprechende Text dazu angezeigt wird ( so wie erwartet ) 
aber ganz am anfang und am ende der skala ( also min oder max auf dem slider gewählt ) 
aus dem text der wert wird.   

Falls das so sein soll ( bei min oder max auf dem slider kommt der Wert statt dem gewünschten Text) 
dann betrachte dieses issue als erledigt.

viele grüße



[slider.txt](https://github.com/Scrounger/ioBroker.vis-materialdesign/files/6155752/slider.txt)

**Comment by Scrounger** [comment]
Du must noch hier was eintragen:
![grafik](https://user-images.githubusercontent.com/6370451/119178724-63e43080-ba6e-11eb-83de-18318541aa06.png)

dann werden die Werte durch labels ersetzt.
