### ISSUE TITLE
Top App Bar - unterschiedliche Darstellung Android/iOS

### ISSUE THREAD

**Issue by Ball-Pic** [Scrounger/ioBroker.vis-materialdesign#157]
Hallo
Ich habe ein kleines Problem mit der Darstellung des Widget "Top App Bar".
Vielleicht hatte schon jemand das Problem und auch eine Erklärung/Lösung.

Ich habe eine VIS gebaut, welche ich gleichermaßen auf Mobiltelefon (Android) als auch Tablet (iOS-iPad) verwende.
Um die Sichten zu steuern habe ich das Widget "Top App Bar" eingesetzt und auch meinem persönlichen Bedarf angepaßt.

Allerdings unterscheidet sich die Darstellung ganz wesentlich zwischen Handy und Tablet.
Es hat den Anschein, daß meine optischen Anpassungen nur für das Tablet (iPad) wirken und das Handy davon nicht mitbekommt (siehe Screenshots).

so sieht es am Handy aus:
![image](https://user-images.githubusercontent.com/81575941/112856236-db6d9300-90af-11eb-851f-9d8c2ed8e90a.png)

und so sieht es am Tablet aus (so sollte es eigentlich auch am Handy sein):
![image](https://user-images.githubusercontent.com/81575941/112856341-fa6c2500-90af-11eb-973e-8a1413e7d42f.png)

Wie gesagt, jemand das Problem bekannt und vielleicht auch eine Erklärung/Lösung parat?

**Comment by Scrounger** [comment]
Du verwendest bei Android die IoBroker App. Hier muss seitens der App die neuste Version der Widgets implementiert sein, siehe auch Doku https://github.com/Scrounger/ioBroker.vis-materialdesign#iobroker-vis-app
