### ISSUE TITLE
"Nur lesend"-Option bei Bool-List-Widget

### ISSUE THREAD

**Issue by BobBruni** [Scrounger/ioBroker.vis-materialdesign#16]
Ich lasse mir mit dem Bool-List einge Status anzeigen. Es wäre sehr hilfreich, wenn man hier auch die Möglichkeit hätte die Option "nur lesend:" zu wählen.

Die Option "Inaktiv(locked)" im Reiter Generell bewirkt nur, dass das Widget im Edit-Modus nicht mehr bedienbar ist. Im Runtime hat dies keine Auswirkungen.

Ich müsste nun ein unsichtbares Widget darüber legen um die bedienbarkeit des Widgets einzuschränken. Dies wäre nur eine unschöne Behelfslösung.

**Comment by Scrounger** [comment]
![grafik](https://user-images.githubusercontent.com/6370451/69496972-24b83c00-0ed8-11ea-85a4-c677730e689c.png)

Option Schalter (nur lesend) & Checkbox (nur lesend) hinzufügen

**Comment by BobBruni** [comment]
![image](https://user-images.githubusercontent.com/58072812/69498341-4a007680-0ee7-11ea-8448-c9eefe65ad7f.png)

Bitte die Option auch für buttonToggle (nur lesend) hinzufügen

**Comment by Scrounger** [comment]
Implementiert in 210425f5a5803f8299cf1ef38164ccf0749a76c1
