### ISSUE TITLE
Dialog: using Datapoint dimming problem

### ISSUE THREAD

**Issue by gaga191281** [Scrounger/ioBroker.vis-materialdesign#161]
Beschreibung:
Wenn man einen Dialog über einen Datenpunkt öffnet, wird wie immer bei Dialogen der Hintergrund der restlichen UI abgedunkelt (wahrscheinlich semi-transparentes Overlay). Wenn der Dialog nun nicht über den 'Schliessen-Button' sondern über den Datenpunkt geschlossen wird, bleibt das Overlay sichtbar, also die UI abgedunkelt.

Reproduzieren:
- Dialog (datapoint) öffnen.
- Dialog über Datenpunkt schliessen

Erwartetes Verhalten:
- Dimming Overlay wird mit Dialog zusammen geschlossen.

Screenshots:
- Initialer Zustand
![Initial](https://user-images.githubusercontent.com/60061155/115683013-4e3bf800-a356-11eb-868c-8089c1d64a55.PNG)

- Dialog geöffnet
![Dialog offen](https://user-images.githubusercontent.com/60061155/115683702-023d8300-a357-11eb-81f0-6478787a8219.PNG)

- Dialog über Datenpunkt geschlossen
![Dialog geschlossen](https://user-images.githubusercontent.com/60061155/115683735-0b2e5480-a357-11eb-8faf-33ac39741914.PNG)

Versionen: 
 - Adapter version: 0.3.19
 - JS-Controller version: 3.2.16
 - Node version: 14.15.5
 - VIS Adapter version: 1.3.8

**Comment by Scrounger** [comment]
In v0.5.x behoben, bitte updaten
