### ISSUE TITLE
Display Issues

### ISSUE THREAD

**Issue by Pix---** [Scrounger/ioBroker.vis-materialdesign#164]
https://github.com/Scrounger/ioBroker.vis-materialdesign/blob/7e7794ad29aba4fb4d5e0dcc045b15f470fbb588/io-package.json#L54

Ansicht: Admin Updates, Spalte "verfügbar" zeigt nicht nur die Version, sondern ohne hover auch die Versionsbeschreibung (siehe Screenshot)

![Bildschirmfoto 2021-05-04 um 09 11 03](https://user-images.githubusercontent.com/8090989/116971834-71ea3100-acba-11eb-8984-0ba5cc763ca2.jpg)

**Comment by Scrounger** [comment]
fixed in 0.5.6
