### ISSUE TITLE
value select widgets - Schriftformatierung

### ISSUE THREAD

**Issue by darkiop** [Scrounger/ioBroker.vis-materialdesign#17]
Schriftfarbe / Schriftart / Schriftgröße bei den 'value selects' über VIS Edit Konfigurierbar machen

https://forum.iobroker.net/topic/26925/test-adapter-material-design-widgets-v0-2-x/58

**Comment by Scrounger** [comment]
5b9c1df03c57a72926cdb77176702b6b33612c71
