### ISSUE TITLE
material design - Button navigation vertical

### ISSUE THREAD

**Issue by MichaelSchaaf999** [Scrounger/ioBroker.vis-materialdesign#172]
Probably not a bug but I am not able to resolve this requirement:
I want to set the color of fonts in the navigation button to a datapoint...  e.g. here:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/53481090/118141309-82608100-b409-11eb-9cae-e58c30debd59.png">
with {0_userdata.0.javascript.Menüsteuerung_WidgCol_Temperaturen}   as the color, this datapoint contains a value like #3d6994.
BUT the result is that the font color always looks like #FFFFF, NOT my required color preset in the datapoint.

What am I doing wrong?

Best regards, Michael

**Comment by Scrounger** [comment]
Please provide more informations.
All i need is described here https://github.com/Scrounger/ioBroker.vis-materialdesign/issues/new?assignees=&labels=&template=bug_report.md&title=%5Bwidget+name%5D%3A+%5Bshort+description%5D

**Comment by MichaelSchaaf999** [comment]
during testing I found a workaround or solution: Different usage of the widget parameters solved this issue.
Thank you!
