### ISSUE TITLE
materialdesign - Top App Bar: special binding „local_*“

### ISSUE THREAD

**Issue by ice987987** [Scrounger/ioBroker.vis-materialdesign#175]
**Describe the bug**
I am still looking for the best configuration of a user independent navigation. With the input of @cdellasanta a working variant could be published [here](https://github.com/ioBroker/ioBroker.vis/issues/370#issuecomment-845264407). But currently there is the following error on every click on the navigation:

`State "local_navigation" has no existing object, this might lead to an error in future versions `

Is there any way to find out if this error comes from the binding "local_*", from the "top app bar navigation“ or from the "view in widget 8"?

**Versions:**  
Adapter version: material design widgets v0.5.6
JS-Controller version: v3.2.16
Node version: v12.22.1
VIS Adapter version: v1.3.8

**Comment by Scrounger** [comment]
> `State "local_navigation" has no existing object, this might lead to an error in future versions `

Mostly this error is shown if there is something wrong with the datapoint. Try to delete it and recreate it, perhaps the error message will be gone.

> Is there any way to find out if this error comes from the binding "local_*", from the "top app bar navigation“ or from the "view in widget 8"?

This error has nothing to do with one of these two widgets, i think ;-)

> **Describe the bug**
> I am still looking for the best configuration of a user independent navigation. With the input of @cdellasanta a working variant could be published [here](https://github.com/ioBroker/ioBroker.vis/issues/370#issuecomment-845264407). But currently there is the following error on every click on the navigation:

Yesterday i also discovered this new feature and did some test. But my result was that values still written to the the datapoint. 
My plan is to analyse deeper the code behind this at the vis adapter.

I think discussion for this would be better in the forum directly than on github. Is certainly also interesting for many other users.
Can you open a new Topic and invite me, please?

**Comment by ice987987** [comment]
Thank you for your support. Much appreciated!

https://forum.iobroker.net/topic/45215/special-binding-local_

**Comment by Scrounger** [comment]
see iob forum for more infos
