### ISSUE TITLE
iObroker iPad App zeigt Material nicht

### ISSUE THREAD

**Issue by TobiasF1986** [Scrounger/ioBroker.vis-materialdesign#19]
Hallo,
ich benutze die offizielle iobroker APP auf meinem iPad 2 um meine vis darzustellen. Ich wollte auf die Material Variante hier umstellen, musste aber feststellen, dass kein einziger Schalter, kein Widget oder sonstiges in der APP auf dem iPad dargestellt wird. In normalen Browsern laden die Schalter, in der APP bleibt alles "blank".

**Comment by Scrounger** [comment]
Muss wahrscheinlich wie bei der Android seitens App integriert werden. Über den Adapter hab da keinen Einfluss drauf. Bitte issue bei der App aufmachen.
