### ISSUE TITLE
Is it possible change HTML Widgets attributes in scripts?

### ISSUE THREAD

**Issue by itProfi** [Scrounger/ioBroker.vis-materialdesign#192]
Hello to all! Is it possible change dinamically attributes in HTML Widgets via scripts? If yes, how is it?
![Скриншот 27-09-2021 131207](https://user-images.githubusercontent.com/6728198/134889954-04e3cfc8-05b9-42f0-98cf-9d6b97e0baf0.png)

**Comment by Scrounger** [comment]
yes that is possible. 

Create a datapoint of type string and write the HTML widget into it by script.
Then you can use it in a Html widget via binding.

You can also use this in all materialdesign widgets that support a json string

**Comment by itProfi** [comment]
> yes that is possible.
> 
> Create a datapoint of type string and write the HTML widget into it by script. Then you can use it in a Html widget via binding.
> 
> You can also use this in all materialdesign widgets that support a json string

Thanks!
