### ISSUE TITLE
[ ioBroker.vis-materialdesign ]: [Installation Skript Das Wetter.js unter Java 5.2.8 nicht möglich?]

### ISSUE THREAD

**Issue by CampoES** [Scrounger/ioBroker.vis-materialdesign#197]
Hi,

ich bin ganz neu bei ioBroker - deshalb könnte meine Frage / meine Fehlermeldung idiotisch sein. Ich möchte 

https://github.com/Scrounger/ioBroker.vis-materialdesign/tree/master/examples/Weather

installieren und habe die Voraussetzungen installieren können, aber bei der Installation scheitere ich nach dem Download von DasWetter.js bei "Installation Skript herunterladen und **unter Skripte anlegen**"

Ich bin bei ioBroker | Skripte | Menü | Skrpte importieren - wähle DasWetter.js aus, aber das Skript wird nicht importiert. Installiert habe ich Java 5.2.8

Alles läuft auf einem Raspberry Pi 3B+

apt-get update / upgrade ist gemacht.

Wo liegt mein Fehler?

Danke für Eure Hilfe.

Michael

**Comment by sigi2345** [comment]
Hallo,

1. auf RAW klicken , dann Strg a dann Strg c 

![Screenshot (4438)](https://user-images.githubusercontent.com/41079106/141600461-eb20dcd0-6f71-4b38-a3a6-21d062d241b1.png)




2. Neues JS Skript anlegen , dann Strg V 
3. Skript speichern

Also nicht die Datei importieren sondern den Inhalt dieser als txt unter einen NEUEN JS Skript anlegen!

**Comment by CampoES** [comment]
Hallo und danke für die Hilfe. 
Da Du einen Screenshot mitgepostet hast konnte ich sehen, dass ich im github-Verzeichnis auf Weather.js klicken musste, um dann die Schaltfläche RAW bedienen zu können. Ich konnte nämlich zunächst mit RAW nichts anfangen.

Das mit dem Kopieren hat dann geklappt.

Beim Start des Skriptes gabs aber Fehlermeldungen. Es fehlte "chroma-js" das ich mit npm install chroma-js im Verzeichnis /opt/iobroker auf dem Raspberry installiert habe. Das Skript lief aber. Ich habe es gestoppt und erneut gestartet. Jetzt kamen nur noch zwei Warnmeldungen:
Datapoint 'pollenflug.0.region#112.summary.json_index_today' not exist
Datapoint 'pollenflug.0.region#112.summary.json_index_tomorrow' not exist!

Das ist auch nach einem weiteren Stop-Start-Zyklus der Fall.

Ich habe dann das Projekt importiert und es läuft.

Vielen Dank
