### ISSUE TITLE
Top App Bar Navigation Drawer aktualisiert iFrame nicht

### ISSUE THREAD

**Issue by BobBruni** [Scrounger/ioBroker.vis-materialdesign#20]
iFrame Widget mit folgenden Link wird dargestellt:
https://wcp.bayerninfo.de/bi/jpg/bi_--a0009_1060_-1444_dinbg_vinbg_---hm-eggenberg_0.jpg

Im View in Widget 8 funktionert der Reload.

**Comment by Smart86** [comment]
My photo of the webcam is unfortunately not updated in the VIS-View

**Comment by Scrounger** [comment]
View in Widget 8 wird in der nächsten Version aus der TopAppBar entfernt. Dann sollten die Probleme behoben sein

**Comment by Smart86** [comment]
Ist damit die nun erschiene Version 0.2.22 gemeint? Hier existiert das Problem aus meiner Sicht leider immer noch.
