### ISSUE TITLE
Widget Button toggle dont work with Safari Browser

### ISSUE THREAD

**Issue by davimas** [Scrounger/ioBroker.vis-materialdesign#21]
Widget Button toggle dont work in Safari Browser.

https://forum.iobroker.net/topic/26925/test-adapter-material-design-widgets-v0-2-x/145

https://forum.iobroker.net/topic/26925/test-adapter-material-design-widgets-v0-2-x/160

**Comment by Scrounger** [comment]
Fehler tritt nur bei iOS Safari, als auf dem iPhone iPad auf?
Kannst du bitte das log von der console Mal hochladen. Hab leider kein iPhone um zu testen. Code review hab ich gemacht, find da allerdings nichts

**Comment by Scrounger** [comment]
Hab es inzwischen selbt auf einem IPad testen können, funktioniert einwandfrei.
