### ISSUE TITLE
Icon face-man fehlt

### ISSUE THREAD

**Issue by Ceel84** [Scrounger/ioBroker.vis-materialdesign#214]
Bitte füge das material design icon "face-man" hinzu

**Comment by Scrounger** [comment]
Ich verwende die https://github.com/Templarian/MaterialDesign-Webfont library (Schriftart). Diese hängt immer ein bissle https://github.com/Templarian/MaterialDesign hinter her.

Einzelne icons kann ich nicht aktiv hinzufügen. D.h. du musst dich immer gedulden bis ich die library aktualsiert habe.
Übergangsweise kannst du diese auch im .svg Optimized format herunterladen und in den MDW Widgets nutzen.
![grafik](https://user-images.githubusercontent.com/6370451/172389086-d11a21e1-6fc3-4fc6-af18-7c0c8e211b69.png)
