### ISSUE TITLE
Top Bar widget content keine weite

### ISSUE THREAD

**Issue by MeisterTR** [Scrounger/ioBroker.vis-materialdesign#22]
Für eine responsive Darstellung ist es zwingend erforderlich das ich in den eingebundenen views width: 100% nutzen kann. gibt es hierfür eine Lösung oder ein workaround?

**Comment by Scrounger** [comment]
Hatte ich hier bereits beantwortet:
https://forum.iobroker.net/topic/25374/neuer-vis-adpater-material-design-widgets/270
