### ISSUE TITLE
ListTemperatureHumid: Luftfeuchtigkeit zeigt "NaN"

### ISSUE THREAD

**Issue by DEV2DEV-DE** [Scrounger/ioBroker.vis-materialdesign#220]
Nach einem Refresh der Seite zeigen alle Widgets zunächst die korrekte Luftfeuchtigkeit.
Nach einer Weile wechseln die Werte dann nach und nach zu "NaN".
Dabei ist es unerheblich, woher die Werte stammen (Gerät, Alias oder eigener DP). Die DP selbst zeigen dabei immer die korrekten Werte.
Zur Überprüfung habe ich einmal ein normales "basic Number" dazugepackt - das zeigt auch brav den korrekten Wert.
![image](https://user-images.githubusercontent.com/95883579/194257921-da521ec3-bf5e-43fd-8f7a-552d60ed48ef.png)

Die Anzeige der Temperatur funktioniert übrigens völlig problemlos.

**Comment by DEV2DEV-DE** [comment]
Um das "Nach einer Weile" zu präzisieren: Das erscheint, sobald sich nach einem Refresh der Seite der Wert für die Luftfeuchtigkeit das nächste mal ändert.

**Comment by djmarc75** [comment]
Auch bei mir wird bei Änderung vom DP "NaN" angezeigt- somit leider im Moment nicht brauchbar.

**Comment by DEV2DEV-DE** [comment]
Asche auf mein Haupt: Falsches Repository :-(
