### ISSUE TITLE
View in Dialog wird (nach Zurückspielen des Backups) nicht mehr angezeigt

### ISSUE THREAD

**Issue by m50434** [Scrounger/ioBroker.vis-materialdesign#235]
Ich habe vor ein paar Tagen ein komplettes Backup von IoBroker neu einspielen müssen.

Seit dem wird leider im MaterialDesign Dialog keine View mehr angezeigt. Der Dialog mit Titel und "Close Button" öffnet sich zwar, die gewählte View ist jedoch nicht zu sehen.

Ich muss dazu sagen, dass ich vor dem Einspielen des Backups eine "alte" Version von Material Design hatte (vielleicht liegt es daran?).
Ich habe jetzt Version 0.5.94 installiert.

Ich habe nun auch versucht, einen neuen Dialog zu erzeugen.
Das Ergbnis bleibt aber leider das Gleiche: Es wird die View nicht angezeigt.

Hier ist ein Export meines benutzten Widgets.

[{"tpl":"tplVis-materialdesign-Vuetify-Dialog-View","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","showDialogMethod":"button","fullscreenResolutionLower":"360","vibrateOnMobilDevices":"50","clickSoundVolume":"0.5","buttonStyle":"raised","mdwButtonPrimaryColor":"var(--materialdesign-widget-theme-color-button-default-primary)","mdwButtonSecondaryColor":"var(--materialdesign-widget-theme-color-button-default-secondary)","textFontFamily":"#mdwTheme:vis-materialdesign.0.fonts.button.default.text","textFontSize":"#mdwTheme:vis-materialdesign.0.fontSizes.button.default.text","imageColor":"#mdwTheme:vis-materialdesign.0.colors.dialog.button_icon","iconPosition":"left","closingClickOutside":"true","backgroundColor":"#mdwTheme:vis-materialdesign.0.colors.dialog.background","headerBackgroundColor":"#mdwTheme:vis-materialdesign.0.colors.dialog.header_background","footerBackgroundColor":"#mdwTheme:vis-materialdesign.0.colors.dialog.footer_background","dividerColor":"#mdwTheme:vis-materialdesign.0.colors.dialog.divider","overlayColor":"#mdwTheme:vis-materialdesign.0.colors.dialog.overlay","showTitle":"true","titleFontSize":"#mdwTheme:vis-materialdesign.0.fontSizes.dialog.title","titleFont":"#mdwTheme:vis-materialdesign.0.fonts.dialog.title","titleColor":"#mdwTheme:vis-materialdesign.0.colors.dialog.header_text","buttonPosition":"flex-end","buttonSize":"medium","buttonFont":"#mdwTheme:vis-materialdesign.0.fonts.dialog.button","buttonFontColor":"#mdwTheme:vis-materialdesign.0.colors.dialog.close_button_text","pressColor":"#mdwTheme:vis-materialdesign.0.colors.dialog.close_button_press","fullscreenCloseIconColor":"#mdwTheme:vis-materialdesign.0.colors.dialog.close_button_icon","fullscreenCloseIconPressColor":"#mdwTheme:vis-materialdesign.0.colors.dialog.close_button_fullscreen_press","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"contains_view":"AdapterStatus","showDialogOid":"0_userdata.0.dialog_landroid_wochenplan","buttontext":"asdasd"},"style":{"left":"1149px","top":"273px"},"widgetSet":"materialdesign"}]

Wie gesagt: Der Dialog ist zu sehen, allerdings wird die View nicht angezeigt:
![grafik](https://user-images.githubusercontent.com/24473301/233767814-7483eb48-e8bc-43f9-a741-2d2a1cbc7117.png)

**Comment by m50434** [comment]
Ich habe mich jetzt dem Problem nochmal angenommen:

Es scheint auf jeden Fall ein Problem mit einer CSS-Klasse zu sein.
Wenn ich im Browser live bei dem Dialog-Fenster die Klasse "vis-widget" rausnehme bzw. in der Klasse "vis-widget" das Attribut "position" von absolute auf z.B. "relative" ändere, werden mir die Elemente der View, die im Dialog angezeigt werden soll, zumindest angezeigt. Zwar dann nicht korrekt, aber sie sind da. 
Grundsätzlich wird die View auch geladen (man kann mit dem Browser über den "Insepktor" im Quelltext sehen, dass die Elemente alle da sind), sie werden nur nicht angezeigt.
Vielleicht hilft das bei der Fehlerfindung?

**Comment by alfiriel** [comment]
Hi, have the same issue here.
I restored backup from few days ago where the dialogs definitely working fine.
@m50434 I will check this today evening

**Comment by alfiriel** [comment]
1. Deleted instance, uninstalled adapter
2. installed adapter, installation log:
>$ iobroker url https://github.com/Scrounger/ioBroker.vis-materialdesign --host palazzoserver --debug

>install Scrounger/ioBroker.vis-materialdesign#8b7529d493f223dfc4f1d1f632553fcb35bbcc92

>NPM version: 8.19.4Installing Scrounger/ioBroker.vis-materialdesign#8b7529d493f223dfc4f1d1f632553fcb35bbcc92... (System call)

>npm WARN skipping integrity check for git dependency ssh://git@github.com/Scrounger/ioBroker.vis-materialdesign.git

>added 1 package, and removed 108 packages in 36s

>upload [21] vis-materialdesign.admin /opt/iobroker/node_modules/iobroker.vis-materialdesign/admin/admin.d.ts admin.d.ts video/mp2t

>upload [20] vis-materialdesign.admin /opt/iobroker/node_modules/iobroker.vis-materialdesign/admin/img/info-big.png img/info-big.png image/png

>upload [14] vis-materialdesign.admin /opt/iobroker/node_modules/iobroker.vis-materialdesign/admin/lib/defaultcolors.json lib/defaultcolors.json application/json

>upload [13] vis-materialdesign.admin /opt/iobroker/node_modules/iobroker.vis-materialdesign/admin/lib/defaultcolorsDark.json lib/defaultcolorsDark.json application/json

>upload [4] vis-materialdesign.admin /opt/iobroker/node_modules/iobroker.vis-materialdesign/admin/style.css style.css text/css

>upload [3] vis-materialdesign.admin /opt/iobroker/node_modules/iobroker.vis-materialdesign/admin/tsconfig.json tsconfig.json application/json

>upload [0] vis-materialdesign.admin /opt/iobroker/node_modules/iobroker.vis-materialdesign/admin/words.js words.js application/javascript

>INFO: Directory "/opt/iobroker/node_modules/iobroker.vis-materialdesign/www" was not found! Nothing was uploaded or deleted.

>Adapter "system.adapter.vis.0" restarted.

>Adapter "system.adapter.web.0" restarted.

>Process exited with code 0
4. Added instance, log:
>$ iobroker add vis-materialdesign auto --host palazzoserver --debug

>INFO: Directory "/opt/iobroker/node_modules/iobroker.vis-materialdesign/www" was not found! Nothing was uploaded or deleted.

>Adapter "system.adapter.web.0" restarted.

>host.palazzoserver create instance vis-materialdesign

>host.palazzoserver object vis-materialdesign.0.lastchange created

>host.palazzoserver object system.adapter.vis-materialdesign.0 created

>Process exited with code 0


6. Still same behavior, dialog not working

**Comment by alfiriel** [comment]
Solved the problem as following:

1. save configuration in instance settings
2. Delete instance and uninstall adapter
3. set repository to beta in expert mode settings
4. searched for vis-materialdesign adapter
5. installed
6. restore configuration in instance settings


@m50434 please test and if working for you, you can close the issue

**Comment by m50434** [comment]
Your workarround worked also for me.
Thank you very much!
