### ISSUE TITLE
Update stable version in repo from 0.0.0 to 0.5.9

### ISSUE THREAD

**Issue by GermanBluefox** [Scrounger/ioBroker.vis-materialdesign#238]
# Think about adding version 0.5.9 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**0.5.9** (744 days old)
**Installs**: stable=**0** (0%), latest=**3738** (58.75%), total=**6363**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

**Comment by mcm1957** [comment]
@Scrounger 
Any reason to not provide this adapter at stable repositories ?

If there is no reaction until 15.12.2023 the adapter could be published at astable anyway.

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 0.5.9 but the current stable version is already 0.5.9.

So this issue should be closed.
