### ISSUE TITLE
Line History Chart: seltsame X-Achsen Einteilung und Werte

### ISSUE THREAD

**Issue by HGlab01** [Scrounger/ioBroker.vis-materialdesign#24]
**Describe the bug**  
Die X-Achse hat keine lineare Einteilung. Bei Flot sieht es anders/richtig aus.
Die History-Daten dazu sind jeweils exakt ein Wert erzeugt mit CronJob 0 */1 (jede volle Stunde) .
Intervall auf 24 Stunden; Aggregate: average

Bsp: bei 02:00 Uhr steht der Punkt zu 02:53 Uhr; 15:00, 17:00, 18:00, 20:00, 23:00 ist nicht linear

![image](https://user-images.githubusercontent.com/54232526/71364298-15daad00-259c-11ea-9c31-1054f1f4f3cb.png)

![image](https://user-images.githubusercontent.com/54232526/71364310-1e32e800-259c-11ea-959d-2ffcb23a8aa3.png)

![image](https://user-images.githubusercontent.com/54232526/71364314-24c15f80-259c-11ea-8d1d-9849921d47ec.png)

![image](https://user-images.githubusercontent.com/54232526/71364593-f4c68c00-259c-11ea-8f04-6c2e16734d8e.png)

**Comment by Scrounger** [comment]
Tritt das Verhalten auch auf, wenn das Zeitinertval verkleinert wird z.B. auf 4 Stunden?

**Comment by HGlab01** [comment]
ja:
![image](https://user-images.githubusercontent.com/54232526/71478978-c346fe00-27f2-11ea-914d-9106eeeeef77.png)

**Comment by Scrounger** [comment]
Die Achsenskalierung wird automatisch von der chart.js api verwaltet, da hab ich keinen Einfluss drauf.
Wo hast du den Parameter `relativeEnd` gefunden? Poste mal den Link.

Der Graph sieht doch jetzt gut aus?

**Comment by HGlab01** [comment]
Achsenskalierung:
11:16 zu 12:00 hat den gleichen Abstand wie 12:00 zu 01:00; das ist nicht wirklich sauber". Wenn mit 11:16 gestartet wird und 4 Stunden eingestellt wird, dann müsste der letzte Punkt 03:16pm sein.
Daher die Vermutung, dass `relativEnd` was nützen könnte.

RelativEnd:
Das entspricht folgender Einstellug im FLOT-UI
![image](https://user-images.githubusercontent.com/54232526/71479926-df4c9e80-27f6-11ea-99aa-19b4cd501ab7.png)
und in der URL sieht es dann so aus:
`&timeType=relative&relativeEnd=today`

**Comment by Scrounger** [comment]
Mach mal nen export (*.csv) von den Daten, muss mir das selbst anschauen.

**Comment by HGlab01** [comment]
klar, gerne!

[data (CSV).txt](https://github.com/Scrounger/ioBroker.vis-materialdesign/files/4002857/data.CSV.txt)

**Comment by Scrounger** [comment]
So hab jetzt ein paar Test gemacht.

1. die Aggregate: average funktion (da verwende ich die vom SQL Adapter / ioBroker interne) bildet mittelwert sowohl für x & y werte, deshalb liegen die Punkte zwischen den Stunden:

![average](https://user-images.githubusercontent.com/6370451/71482451-f2656b80-2802-11ea-8707-61e620699fb0.png)

2. wenn ich Aggregate: minmax verwende, dann liegen die Punkte sauber auf der entsprechenden x-Achsen linie:

![example2](https://user-images.githubusercontent.com/6370451/71482515-3b1d2480-2803-11ea-89bf-0f8000b35bc4.png)

Das Problem das am Ende die x-Achse nicht mehr sauber dargestellt wird, ist das er immer die aktuelle Uhrzeit nimmt. Da muss ich mal schauen ob ich das so umbauen kann, das er die Zeit des letzten Wertes nimmt.

Bessere Ergebnisse erhälst du auch, wenn du das 'Zeitformat der x-Achse' anpasst:
![example1](https://user-images.githubusercontent.com/6370451/71482533-59832000-2803-11ea-9893-793a7f173494.png)

**Comment by Scrounger** [comment]
Hab den Fehler glaub gefunden. Test mal den aktuellen master branch.

**Comment by HGlab01** [comment]
Ich hab es jetzt gerade über
https://github.com/Scrounger/ioBroker.vis-materialdesign/
installier (das meintest du  mit Master?). Leider gibt es die Verzerrung auf der Achse immer noch:
![image](https://user-images.githubusercontent.com/54232526/71488903-526c0a00-2823-11ea-8b37-5895acc17659.png)

Auch wenn ich "min" eingestellt habe:
![image](https://user-images.githubusercontent.com/54232526/71488942-70d20580-2823-11ea-9401-8a1f6a31f362.png)

**Comment by sigi2345** [comment]
![Screenshot (1045)_LI](https://user-images.githubusercontent.com/41079106/71489277-146fe580-2825-11ea-9935-3867d2221c66.jpg)

**Comment by HGlab01** [comment]
@sigi2345 Die Version habe ich, jedoch gibt es die Version schon seit 6 Stunden, der Fix ist aber erst 2 ode 3 Stunden alt.

**Comment by Scrounger** [comment]
@HGlab01 

Hab jetzt extra die versionsnummer noch hochgezogen.
Installieren musst du über die 'Katze' -> version muss dann 0.2.23 sein.
Und danach iobroker neustarten, damit sicher alle Änderungen übernommen werden. Dann im VIS Editor einmal den graph auswählen, irgendwas verändern, speichern und runtime starten.

Bin mir ziemlich sicher das es funktioniert, weil es mit deinen Daten das gwünschte Ergebnis liefert:
![grafik](https://user-images.githubusercontent.com/6370451/71491117-29ea0d00-282f-11ea-8949-2245b7db5521.png)

**Comment by HGlab01** [comment]
stimmt, sieht schon DEUTLICH besser aus.
Was mir dabei noch auffällt:
1) erster Punkt ist um 10:54; letzter Punkt um 10:04; sind keine 24 Stunden, daher sind die Punkte auch schwer gleich zu verteilen
![image](https://user-images.githubusercontent.com/54232526/71513106-5470b000-2899-11ea-97a1-0dd5f62b73b1.png)

![image](https://user-images.githubusercontent.com/54232526/71513004-e3c99380-2898-11ea-8070-85e08498a2e1.png)

2) am Beginn der Achse gibt es zwei Punkte: 10:54 und 11:02
![image](https://user-images.githubusercontent.com/54232526/71513135-69e5da00-2899-11ea-8bc8-63cf1d72d4aa.png)

![image](https://user-images.githubusercontent.com/54232526/71513013-ee842880-2898-11ea-905d-3581b695a8e9.png)

![image](https://user-images.githubusercontent.com/54232526/71513017-f512a000-2898-11ea-8603-7b0d9e3a4592.png)

**Comment by Scrounger** [comment]
zu 1.)
Das Stimmt so nicht. Der Graph wurde um 10:54 das letzte mal aktualisiert. Der letzte Datenpunkt ist halt von 10:04. Sind also volle 24 Stunden. Deshlab ist dann rechts auch eine Lücke zum letzten Punkt.
Vergleiche meinen Graph im Post davor.

zu 2.)
Der erste Punkt um 10:54 liegt eigentlich bei 10:0x. Die getHistory (aggregation) Funktion nimmt aber den letzten Punkt und setzt diesen an den Anfang des abgefragten Zeitraumes. Das ist auch gut so, weil sonst hätte man eine Lücke im Graph, obwohl ja außerhalb des abgefragten Zeitraumes bereits Daten existieren. Der nächste Datenpunkt wird um 11:0x aufgenommen. Von daher korrekt das diese beiden Punkte so dicht beieinander liegen.

Mit der folgenden Option kannst du auch noch einstellen ob die Achse an den Daten oder an der Beschriftung sich vorangig orientieren soll:
![grafik](https://user-images.githubusercontent.com/6370451/71520676-8f84da80-28bd-11ea-91a3-0eeddb2ff619.png)


Für mich ist der Punkt erledigt.

**Comment by HGlab01** [comment]
Hi @Scrounger 

ad 1) Die Datenpunkte sind alle um xx:59:59; also eine Sekunde vor jeder vollen Stunde. Es gibt nur genau diese Datenpunkte

ad 2) Skalengrenze: Datensatz habe ich bereits in Verwendung
Die beiden nah aneinander liegenden Punkte gibt es nicht. Jeder Punkt ist exakt 60 Minuten vom nächsten entfernt, siehe 1)

**Comment by Scrounger** [comment]
1.) hatte ich oben bereits erwähnt, wenn du als aggregation average auswählst, dann erstellt er das mittel aus x & y Wert. Wenn du z.B. minmax wählst dann liegen die Punkte exakt auf jeder vollen stunde.

2.) Hast du 2. oben gelesen ?! Da ist erklärt warum es diesen Punkt gibt.

**Comment by HGlab01** [comment]
Nutze MIN, hab es jetzt auch mit MINMAX probiert. Sieht gleich aus.
Datensatz mit Skalengrenze ist auch eingestellt.
Klar hab ich ad 2) gelesen aber dann wohl falsch verstanden.
Ganz naiv wäre für mich die Wahl der Datenpunkte wie folgt:
Von Now bis Now-24Stunden nimm alle Punkte und trage sie auf eine Skala von Now-24Stunden bis Now auf.
Punkte vor Now-24Stunden werden komplett ignoriert.
Aber DANKE für deine Mühen @Scrounger!
