### ISSUE TITLE
[Select] Objekt vom typ werteliste "koppeln"

### ISSUE THREAD

**Issue by darkiop** [Scrounger/ioBroker.vis-materialdesign#25]
Erweiterung um eine Version des 'value select' analog dem 'jqui select value list':

![grafik](https://user-images.githubusercontent.com/205119/71438073-87c60a00-26f4-11ea-8835-749afd7f12ac.png)

= dynamische value list über einen DP.

**Comment by Scrounger** [comment]
enthalten in 159c3dc
