### ISSUE TITLE
Slider: Knopf bewegt sich beim Bewegen nicht mit

### ISSUE THREAD

**Issue by DevChannel-de** [Scrounger/ioBroker.vis-materialdesign#29]
Wenn beim Slider der Knopf gehalten wird, bewegt sich der Knopf nicht mit und dadurch weiß man nicht, welchen Wert man einstellt. Erst beim Loslassen sieht man, welchen Wert man wirklich "erwischt" hat.

**Comment by Scrounger** [comment]
Brauch das komplette consolen log des browsers zur laufzeit.

**Comment by Strobelix80** [comment]
Gleiches Problem bei ios Safari, wenn der Slider in einem Dialog angezeigt wird. Wenn du mir jetzt sagst, wie ich den conolen log aus dem Handy bekomme, helf ich gern weiter

**Comment by Scrounger** [comment]
https://www.google.de/search?ei=bBUGXobhN76Lk74P1PSxwAQ&q=iphone+safari+console+log&oq=iphone+safari+console&gs_l=psy-ab.3.1.0l2j0i22i30l8.5176.14162..16088...0.3..0.93.2419.29......0....1..gws-wiz.......0i71j0i8i7i30j0i13i30j0i8i13i30j0i67j0i131.qguc_er0cW0

**Comment by Scrounger** [comment]
Bitte aktuellen master branch testen (v0.2.24)!

**Comment by DevChannel-de** [comment]
Habe jetzt auf 0.2.24 ge-updated - leider keine Änderung.
Vielleicht ein Hinweis, der hilft: wenn ich mit der Maus (oder Finger) auf der Linie an eine Stelle klicke (tippe), wird der Wert geändert und die Position des Knopfes erfolgreich ändert sich.

In den Logs fällt mir auf, dass dort immer noch "Version vis-materialdesign: 0.2.22" steht. Im ioBroker-Admin ist es aber definitiv 0.2.24. Browser-Cache habe ich auch gelöscht:

![image](https://user-images.githubusercontent.com/57469720/71541622-3324c800-295c-11ea-80e9-b4fee7e317e1.png)

...dann kommen ganz viele "Create inner vis object..."-Einträge und dann am Ende:

![image](https://user-images.githubusercontent.com/57469720/71541632-71ba8280-295c-11ea-9847-f448d79f2aef.png)


Und, mit was ich teste:
- Windows 10 Desktop
- Android Tablet
- iOS iPhone

**Comment by Scrounger** [comment]
Dann starte Mal iobroker neu. Es muss in der console die gleiche Version stehen

**Comment by DevChannel-de** [comment]
Ja, nach dem Durchstarten der vis-Instanz zieht jetzt die 24 und das Problem ist gelöst :-)
