### ISSUE TITLE
[Slider] Ungenaue Beschriftung im neuen Slider Widget

### ISSUE THREAD

**Issue by Steff42** [Scrounger/ioBroker.vis-materialdesign#32]
Im neuen Slider-Widget kann die Ausrichtung per Dropdown ausgewählt werden.
Es gibt dort >**horizontal**< und >**senkrecht**< hier wäre statt >**senkrecht**< >**vertikal**< besser oder anstatt >**horizontal**< eben >**waagerecht**<.

Ansonsten sind die Möglichkeiten, die der Adapter biete Wahnsinn, mache meine ersten Gehversuche damit und entdecke immer neue Dinge!
Gruß Steffen

**Comment by Scrounger** [comment]
Das ist die default Übersetzung für horizontal & vertical seitens ioBroker. Diese möchte ich nur ungern "überschreiben".
Bitte erstell ein Issue direkt beim iobroker.admin adapter, damit die default übersetzung angepasst wird:
https://github.com/ioBroker/ioBroker.admin
