### ISSUE TITLE
Bug im neuen Top App Bar Drawer?

### ISSUE THREAD

**Issue by Steff42** [Scrounger/ioBroker.vis-materialdesign#33]
Ich bin gerade am basteln mit dem neuen Top App Bar Drawer, dabei ist mir beim erstellen der Untermenüs aufgefallen, das ich in den Feldern wo laut Anleitung die Views getrennte mit einem "|" eingegeben werden sollen nur eine Zahl eingegeben werden kann.
![image](https://user-images.githubusercontent.com/35137293/71619588-5c945c80-2bc5-11ea-8001-56e67aed6fe7.png)
In der alten Version des Top App Bar Drawers kann ich in die Felder auch Text eingeben.
Ich habe die Version 0.2.25 vom vis-materialdesign installiert.
Gruß Steffen

**Comment by darkiop** [comment]
Das passt so, im submenuCounts trägst du die Anzahl der gewünschten Menüpunkte ein - der Index für die Listenelemente wird an dieser Stelle entsprechend erhöht. Im 'view in widget 8' wird dann der view eingetragen.

**Comment by Scrounger** [comment]
@Steff42 
Ja das ist die "neue" AppBar, wo ich das view in widget 8 wieder herausgelöst habe. Hab bis jetzt die Doku noch nicht angepasst.

Hier gibts bei den letzten Post eine Erklärung wie es funktioniert
https://forum.iobroker.net/topic/26925/test-adapter-material-design-widgets-v0-2-x/345
