### ISSUE TITLE
value select - Hintergrundfarbe

### ISSUE THREAD

**Issue by darkiop** [Scrounger/ioBroker.vis-materialdesign#34]
Beim aktuellen 'value select' kann im Standard-Modus keine Hintergrundfarbe eingestellt werden. Im 'outlinded' ist dies möglich.

![grafik](https://user-images.githubusercontent.com/205119/71619899-032d2d00-2bc7-11ea-9380-f60ca876cc39.png)

**Comment by Scrounger** [comment]
Fix in d8d816e
