### ISSUE TITLE
[Dialog] Buttons unter Dialog können nicht bedient werden

### ISSUE THREAD

**Issue by skokarl** [Scrounger/ioBroker.vis-materialdesign#35]
Die Button Toogle und Button State lassen sich nicht mehr bedienen wenn die
Dialogview, nicht sichtbar, darüber liegt.
Evtl. betrifft es noch mehr Widgets. Die Dialog View ist also nicht sichtbar, verhindert
aber teilweise die Bedienung der View.

**Comment by Scrounger** [comment]
Kann ich nicht bestätigen, denke ist ein z-index problem in deiner view.

![dialog](https://user-images.githubusercontent.com/6370451/71646811-0b7f8800-2ced-11ea-9f1d-5d9e6cb329d0.gif)

**Comment by gaga191281** [comment]
Kann geändert werden wenn die ObjektID der Sichtbarkeit an die selbe Variable wie der Boolsche Schalter zum Öffnen des Dialogs gehängt wird

**Comment by skokarl** [comment]
erledigt.
Z-Index stand default auf 1000. Bitte schliessen.
