### ISSUE TITLE
Slider wird im web angezeigt, auf dem Handy nicht

### ISSUE THREAD

**Issue by daendaen** [Scrounger/ioBroker.vis-materialdesign#37]
Hi,

der neue Slider funktioniert auf dem Laptop super, auf meinem Handy (vis app) sehe ich allerdings nichts. Kann man das irgendwie beheben?

VG

**Comment by Scrounger** [comment]
Das liegt an der vis App. Da geht der Adapter noch nicht. Das muss seitens App implementiert werden.
Aktuell auf dem Handy nur Überbrowser möglich.
