### ISSUE TITLE
http://iobroker.click:8082/vis/index.html?Material%20Design%20Widgets not working

### ISSUE THREAD

**Issue by HGlab01** [Scrounger/ioBroker.vis-materialdesign#40]
Yesterday I was able to connect to
http://iobroker.click:8082/vis/index.html?Material%20Design%20Widgets
and it is/was very helpful to optimize my views.
The side is no longer available. Ping to iobroker.click works [194.39.186.21].
Calling http://iobroker.click:8082/vis/index.html ends with "Connecting to Server..."
Calling http://iobroker.click:8082/vis/index.html?Material%20Design%20Widgets ends with:
![image](https://user-images.githubusercontent.com/54232526/71874101-50f2e980-3121-11ea-92fa-be3655c30f7a.png)

**Comment by Scrounger** [comment]
The site is hosted by iobroker. I still use them to show whats possible with the adapter.
I will add an alternativ link as fallback to the documentation and editor in next release
