### ISSUE TITLE
Top App Bar Navigation Drawer

### ISSUE THREAD

**Issue by mark77-DE** [Scrounger/ioBroker.vis-materialdesign#42]
Moin,

die Bar verdeckt den Editor, scheinbar eigal, welchen Z-Index sie bekommt.

![2020-01-08_08h05_22](https://user-images.githubusercontent.com/31760710/71957307-adbbd600-31ed-11ea-9cfb-07c77c0bff05.png)

Gibt es eine Möglichkeit, die "[xyz]" vor den Menüeinträgen verschwinden zu lassen?

![2020-01-08_08h07_44](https://user-images.githubusercontent.com/31760710/71957403-f83d5280-31ed-11ea-8b7e-cc61161eff9b.png)

Gruß,
Mark

P.S: Top Arbeit, Danke!!!

**Comment by Scrounger** [comment]
Das ist leider so wenn man eine relative breite verwendet.
