### ISSUE TITLE
line chart - Linie zwischen Punkten ohne Daten

### ISSUE THREAD

**Issue by darkiop** [Scrounger/ioBroker.vis-materialdesign#43]
Ich hatte heute Nacht eine downtime des ioBroker Controllers, entsprechend gibt es für die Werte der CPU/RAM Auslastung keine Einträge in der DB. Im Diagram ist definiert das die Linie zwischen Werten ohne Punkte nicht gezogen werden soll - beim Rendern geschieht dies aber trotzdem:

![grafik](https://user-images.githubusercontent.com/205119/72679720-29e9cf80-3ab2-11ea-8914-49789a02d615.png)

**Comment by Scrounger** [comment]
kann ich nicht reproduzieren, funktioniert:
![chart](https://user-images.githubusercontent.com/6370451/72830853-eba30a80-3c81-11ea-99c4-c78ad7868860.gif)

Bitte folgendes testen:
- Linen zeichnen deaktiviern und wieder aktivieren

Ist die Option in der Instanz des SQL Adapters aktiviert?
![grafik](https://user-images.githubusercontent.com/6370451/72831053-53f1ec00-3c82-11ea-8a42-e6cd7ad57e91.png)

Welche SQL Adapter verwendest du?

Wie sehen die SQL Rohdaten aus, vor und nach der Lücke?

**Comment by darkiop** [comment]
>Ist die Option in der Instanz des SQL Adapters aktiviert?
Nein die ist nicht aktiv.

Adapter ist der SQL-Adapter (MariaDB).

Rohdaten sind Zahlen (ts_numbers).

**Comment by Scrounger** [comment]
> > Ist die Option in der Instanz des SQL Adapters aktiviert?
> Nein die ist nicht aktiv.

Daran liegt es. Es muss zwingend ein `null` wert geschrieben werden, damit die API das als Lücke interpretiert.
