### ISSUE TITLE
[Dialog] view leer nach View wechsel

### ISSUE THREAD

**Issue by gaga191281** [Scrounger/ioBroker.vis-materialdesign#44]
**Describe the bug**  
Bei einem Wechsel einer View in eine andere über die "top app bar" und wieder zurück ist beim Öffnen eines Dialoges dieser leer. Lediglich Überschrift und Schließen-Button sind noch zu sehen. Alle Komponenten wie Buttons, etc. sind weg. Es hilft nur ein Neuladen der Seite.

**To Reproduce**  
1. Dialog-View aus View1 öffnen
2. Dialog-View schließen
3. Über Top-app-bar in View2 wechseln
4. Über Top-app-bar zurück in View1 wechseln
5. Dialog-View öffnen

**Expected behavior**  
Dialog-View sollte wie beim ersten Aufruf aussehen, ist jedoch bis auf "title" und "close"-Button leer.

**Comment by Scrounger** [comment]
Ficed with new dialog view
