### ISSUE TITLE
[Masonry Views] Bedingungen für sichtbarkeit der Views

### ISSUE THREAD

**Issue by BobBruni** [Scrounger/ioBroker.vis-materialdesign#47]
Es wäre sehr hilfreich, wenn man zusätzlich zu den einzelnen Cards Einstellungen zur Sichtbarkeit machen könnte, um diese bedingt auszublenden oder anzuzeigen:

![image](https://user-images.githubusercontent.com/58072812/73592710-40a21480-44fd-11ea-8668-1a7e603a0c8b.png)

**Comment by Scrounger** [comment]
1. sichtbar in Abhängigkeit der Auflösung, z.B. Auflösung > x, dann view zeigen
2. per Objekt steuern

**Comment by Scrounger** [comment]
>     1. sichtbar in Abhängigkeit der Auflösung, z.B. Auflösung > x, dann view zeigen

in 31f3a3c00d9ef126a3ba356b32cc1043ac5a3292 enthalten

**Comment by Scrounger** [comment]
>     2. per Objekt steuern

in 101f42c7f6ae398f2f5396e88ce14cfb0fbbd866 enthalten
