### ISSUE TITLE
Dimmerfunktion in List anbieten

### ISSUE THREAD

**Issue by OMCastle** [Scrounger/ioBroker.vis-materialdesign#48]
Hallo, besteht die Möglichkeit, neben den "Schaltern" in "List" einen kleinen Slider darzustellen? So kann man direkt eine Dimmbare Lampe steuern. Manche Lampen haben leider keine On/Off funktion, um zum letzten gedimmten Wert zurückzukehren.

**Comment by BobBruni** [comment]
Schließe mich an! Auch für Rollos wäre das super!!!

**Comment by Scrounger** [comment]
Leider unterstützt das die API nicht. Und das selbst reinzubasteln ist extrem aufwendig.

Möglich Lösung wäre z.B. switch nehmen und per skript für true dem dimmer den Wert X zuweisen.

Oder nehmt ne Liste und setzt einfach die benötigten slider dahinter, sieht dann so aus:
![grafik](https://user-images.githubusercontent.com/6370451/73611531-07dc6b00-45e3-11ea-9425-b7e7cb1d789b.png)
