### ISSUE TITLE
unexpected behavior of Masonry-Views with 3 views and 2 columns

### ISSUE THREAD

**Issue by HGlab01** [Scrounger/ioBroker.vis-materialdesign#49]
**Describe the bug**  
The behavior of Masonry-Views with 3 views and 2 columns is unexpected if distance between views > 0 (if it is 0 then it works)
Result: 
Edit-Mode: 1+2 in column 1, 3 in column 2
Runtime: 1 in column 1, 2+3 in column 2

Edit:
![image](https://user-images.githubusercontent.com/54232526/73632070-0c446a80-465b-11ea-900b-11292963483c.png)

Runtime:
![image](https://user-images.githubusercontent.com/54232526/73631786-4d884a80-465a-11ea-9517-655f9679e571.png)

**To Reproduce** 
View: 
`{
  "settings": {
    "style": {
      "background_class": ""
    },
    "theme": "redmond",
    "sizex": "",
    "sizey": "",
    "gridSize": "",
    "snapType": null
  },
  "widgets": {
    "e00001": {
      "tpl": "tplVis-materialdesign-Masonry-Views",
      "data": {
        "g_fixed": true,
        "g_visibility": false,
        "g_css_font_text": false,
        "g_css_background": false,
        "g_css_shadow_padding": false,
        "g_css_border": false,
        "g_gestures": false,
        "g_signals": false,
        "g_last_change": false,
        "visibility-cond": "==",
        "visibility-val": 1,
        "visibility-groups-action": "hide",
        "countCols": "2",
        "countViews": "2",
        "viewAlignment": "left",
        "signals-cond-0": "==",
        "signals-val-0": true,
        "signals-icon-0": "/vis/signals/lowbattery.png",
        "signals-icon-size-0": 0,
        "signals-blink-0": false,
        "signals-horz-0": 0,
        "signals-vert-0": 0,
        "signals-hide-edit-0": false,
        "signals-cond-1": "==",
        "signals-val-1": true,
        "signals-icon-1": "/vis/signals/lowbattery.png",
        "signals-icon-size-1": 0,
        "signals-blink-1": false,
        "signals-horz-1": 0,
        "signals-vert-1": 0,
        "signals-hide-edit-1": false,
        "signals-cond-2": "==",
        "signals-val-2": true,
        "signals-icon-2": "/vis/signals/lowbattery.png",
        "signals-icon-size-2": 0,
        "signals-blink-2": false,
        "signals-horz-2": 0,
        "signals-vert-2": 0,
        "signals-hide-edit-2": false,
        "lc-type": "last-change",
        "lc-is-interval": true,
        "lc-is-moment": false,
        "lc-format": "",
        "lc-position-vert": "top",
        "lc-position-horz": "right",
        "lc-offset-vert": 0,
        "lc-offset-horz": 0,
        "lc-font-size": "12px",
        "lc-font-family": "",
        "lc-font-style": "",
        "lc-bkg-color": "",
        "lc-color": "",
        "lc-border-width": "0",
        "lc-border-style": "",
        "lc-border-color": "",
        "lc-border-radius": 10,
        "lc-zindex": 0,
        "View0": "A1",
        "View1": "A2",
        "viewsHeight0": "350",
        "viewsHeight1": "350",
        "viewsWidth0": "",
        "class": "",
        "viewsWidth1": "",
        "showResolutionAssistant": false,
        "desktopGaps": "5",
        "handyPortraitWidth": "720",
        "handyPortraitCols": "1",
        "handyPortraitGaps": "",
        "tabletPortraitCols": "2",
        "tabletLandscapeCols": "2",
        "tabletLandscapeGaps": "",
        "View2": "A3",
        "viewsHeight2": "350",
        "tabletPortraitGaps": "5"
      },
      "style": {
        "left": "0",
        "top": "0",
        "width": "100%",
        "height": "100%",
        "overflow-y": "auto"
      },
      "widgetSet": "materialdesign"
    }
  },
  "name": "B",
  "filterList": []
}`

A1 (A2 and A3 are equal):
`{
  "settings": {
    "style": {
      "background_class": ""
    },
    "theme": "redmond",
    "sizex": "",
    "sizey": "",
    "gridSize": ""
  },
  "widgets": {
    "e00001": {
      "tpl": "tplVis-materialdesign-Card",
      "data": {
        "g_fixed": false,
        "g_visibility": false,
        "g_css_font_text": false,
        "g_css_background": false,
        "g_css_shadow_padding": false,
        "g_css_border": false,
        "g_gestures": false,
        "g_signals": false,
        "g_last_change": false,
        "visibility-cond": "==",
        "visibility-val": 1,
        "visibility-groups-action": "hide",
        "titleLayout": "headline6",
        "subtitleLayout": "subtitle2",
        "cardLayout": "Basic",
        "cardStyle": "outlined",
        "signals-cond-0": "==",
        "signals-val-0": true,
        "signals-icon-0": "/vis/signals/lowbattery.png",
        "signals-icon-size-0": 0,
        "signals-blink-0": false,
        "signals-horz-0": 0,
        "signals-vert-0": 0,
        "signals-hide-edit-0": false,
        "signals-cond-1": "==",
        "signals-val-1": true,
        "signals-icon-1": "/vis/signals/lowbattery.png",
        "signals-icon-size-1": 0,
        "signals-blink-1": false,
        "signals-horz-1": 0,
        "signals-vert-1": 0,
        "signals-hide-edit-1": false,
        "signals-cond-2": "==",
        "signals-val-2": true,
        "signals-icon-2": "/vis/signals/lowbattery.png",
        "signals-icon-size-2": 0,
        "signals-blink-2": false,
        "signals-horz-2": 0,
        "signals-vert-2": 0,
        "signals-hide-edit-2": false,
        "lc-type": "last-change",
        "lc-is-interval": true,
        "lc-is-moment": false,
        "lc-format": "",
        "lc-position-vert": "top",
        "lc-position-horz": "right",
        "lc-offset-vert": 0,
        "lc-offset-horz": 0,
        "lc-font-size": "12px",
        "lc-font-family": "",
        "lc-font-style": "",
        "lc-bkg-color": "",
        "lc-color": "",
        "lc-border-width": "0",
        "lc-border-style": "",
        "lc-border-color": "",
        "lc-border-radius": 10,
        "lc-zindex": 0,
        "title": "A1"
      },
      "style": {
        "left": "0",
        "top": "0",
        "width": "100%",
        "height": "100%"
      },
      "widgetSet": "materialdesign"
    }
  },
  "name": "A1",
  "filterList": []
}`

**System**
ioBroker.vis-materialdesign: 0.2.50
JS-Controller: 2.2.8
Admin: 3.7.8
Node/Node.js: 10.18.1
OS: Linux Ubuntu 18.04.3 LTS
Hardware: x64, Intel Core i3

**Comment by Scrounger** [comment]
Fixed in f469b80c04dc687dde9eeb5854345ec35b571103

A note for the height of the individual views (A1, A2, etc.) must indicate a fixed height. This height must then be set in the Masnory widget for the corresponding view.

**Comment by HGlab01** [comment]
Cools, thanx! Works now!
To be honest... I do not understand your note :-)
