### ISSUE TITLE
[List] Farbänderung Switches

### ISSUE THREAD

**Issue by Mic-M** [Scrounger/ioBroker.vis-materialdesign#54]
Siehe auch hier: https://forum.iobroker.net/post/374640

Wünschenswert wäre die farbliche Anpassungs-Möglichkeit der Schalter (Switches).
Hier der Workaround mit CSS:
```
.mdc-switch.mdc-switch {
    --materialdesign-color-switch-off:green; 
    --materialdesign-color-switch-track:#fff;
}
.mdc-switch.mdc-switch--checked {
    --materialdesign-color-switch-on:red; 
}
```
Links vorher, rechts nachher:
![switchesmd](https://user-images.githubusercontent.com/39859059/74108187-e7c72180-4b77-11ea-9dc0-d60b47532bd7.png)

Danke

**Comment by Scrounger** [comment]
enthalten in 9ec03b8ba095b8f5f0fed5e73ededf29d364a0b5
