### ISSUE TITLE
[Table] connect with data from ioBroker.history

### ISSUE THREAD

**Issue by HGlab01** [Scrounger/ioBroker.vis-materialdesign#55]
Would be great if ioBroker.history could feed the Table widget like it is implemented in "vis-history".

**Comment by Scrounger** [comment]
This can be done by a script. Creating a json string used by the table widget.

**Comment by HGlab01** [comment]
Would be great if you could take your time to provide a snippet how to do it!

**Comment by Scrounger** [comment]
use the getHistory function
https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#gethistory

iterate through the data and create a json string for the table
