### ISSUE TITLE
Add Push-Button "Taster" as setting

### ISSUE THREAD

**Issue by IO-Link** [Scrounger/ioBroker.vis-materialdesign#58]
Add the Push-Button funcionality to the common settings of the "Button Toogle". Like it is done in hqwidgets "On/Off". 

Bei den widgets "hqwidgets" gibt es beim Button on/off die Funktion "Taster" in den allgemeinen Einstellungen. Für mich ist die sehr hilfreich, da ich öfter mit Tastern arbeite.

**Comment by Scrounger** [comment]
Versteh ich nicht. Kann doch ebenso als Taster verwendet werden. Man darf dann halt keine Icon / Farbe für on angeben, dann ist das ein Taster.

Bitte genaues Beispiel angeben und wie dann damit der Datenpunkt geschaltet werden soll, also angeben welche. Zustand die Werte annehmene sollen

**Comment by IO-Link** [comment]
**IST:** Beim "materialdesign - Button Toolge" wechselt der Datenpunkt bei jedem Drücken von false auf true und wieder auf false
1. Button gedrückt = true
2. Button nicht mehr gedrückt = true
3. Button gedrückt = false

**SOLL:** Es soll ein Datenpunkt (state, boolean (true/false)) nur dann von false auf true wechseln, wenn der entsprechende Button im VIS gedrückt ist. 

1. Button gedrückt = true
2. Button nicht (mehr) gedrückt = false
3. Button gedrückt = true
D.h. der Datenpunkt soll nur solange true sein, solange der Button im VIS gedrückt ist.

Beim "hqwidget - On/Off" gibt es bei den Eigenschaften die Option "Taster". Dann reagiert dieser wie oben gewünscht.
![image](https://user-images.githubusercontent.com/45272881/74769260-5ef06a00-528a-11ea-91ba-0c4a3762275e.png)

**Comment by Scrounger** [comment]
OK jetzt hab ich es verstanden. Kann ich einbauen.

**Comment by Scrounger** [comment]
enthalten in c89f1423d96b63d52010fef55729ac40c2f02935
