### ISSUE TITLE
Icon List / List Symbol und Zustand aktualisiert nicht nach Datenpunktänderung Button Toggle

### ISSUE THREAD

**Issue by Gompman** [Scrounger/ioBroker.vis-materialdesign#63]
Zustand/Symol in VIS sollte synchron mit dem Wert im Datenpunkt des Objektes sein.

Wird der Datenpunkt im Admin Bereich z.B. geändert wird dies auf der VIS nicht nachgezogen.

**Comment by Scrounger** [comment]
Ich versteh nur bahnhof...

Welches Widget?
Wie sind die Einstellungen des Widgets?
Genaue Beschreibung wann der Fehler auftritt - Schritt für Schritt?
Welcher Browser?
Welche Version des Adapters?
Consolen Log des Browsers zur Verfügung stellen.

**Comment by Gompman** [comment]
Widget: bool Icon List & bool List
[Einstellungen Icon List.txt](https://github.com/Scrounger/ioBroker.vis-materialdesign/files/4270274/Einstellungen.Icon.List.txt)
Browser: Firefox 73.0.1
Adapter Version: 0.2.59

Beschreibung: 

1. Beleuchtung über Materialdesign Icon List widget angeschaltet -> Licht geht an & Symbol ändert sich auch passend
2. Schalten der Beleuchtung durch einen Hardware Wandtaster oder Browser von einem anderen Gerät (anderes widget nicht material Design) oder aber direkt im Admin Bereich von iobroker den Datenpunkt wieder auf "aus" gestellt.
3. Beleuchtung ist aus. Materialdesign Widget änder aber das Symbol nicht auf "aus"

Toggeln des Wertes funktioniert aber ohne Probleme

Aber sehr cooles Projekt.

**Comment by Scrounger** [comment]
Kann des nicht reproduzieren. Poste Mal die RAW Daten des Datenpunktes

**Comment by Scrounger** [comment]
Inzwischen konnte ich es glaub reproduzieren. Wenn der Datenpunkt nicht vom typ boolean ist, musst du als Type eine der folgenden Optionen auswählen:

![grafik](https://user-images.githubusercontent.com/6370451/75622446-991e0d80-5ba0-11ea-863b-849056295374.png)

**Comment by Gompman** [comment]
Hier nochmal die RAW Daten des Datenpunktes (werden vom KNX Adapter so angelegt als STATE)

{
  "from": "system.adapter.knx.0",
  "ts": 1531581164377,
  "common": {
    "name": "OG-Büro-Deckenbeleuchtung-schalten",
    "type": "boolean",
    "role": "level",
    "min": 0,
    "max": 1,
    "read": false,
    "write": true
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "0/1/24",
    "addressRefId": "P-0546-0_GA-295",
    "statusGARefId": "P-0546-0_GA-301",
    "actGARefId": ""
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.Licht.Schalten_(Ein_Aus).OG-Büro-Deckenbeleuchtung-schalten",
  "type": "state"
}

Das klappt leider auch nicht. Im KNX Bereich gibt es vielleicht eine Besonderheit die einfluss darauf hat. in der KNX Welt werden zwei Datenpunkte erzeugt einmal zum setzen und der andere der den Status des Schaltaktors besitzt. der KNX Adapter packt diese beiden dann im IOBROKER zusammen siehe : "addressRefId": "P-0546-0_GA-295",
    "statusGARefId": "P-0546-0_GA-301",
Vielleicht liegt es daran das der Daten punkt im Iobroker nicht als lesend angehakt ist.

Wenn ich die Seite im Browser aber neulade F5 dann aktualisiert er passend den status.

**Comment by Scrounger** [comment]
Also ich hab des jetzt mit deinem Datenpunk getestet. Funktioniert einwandfrei.

Hast du die raw 1:1 kopiert?
Weil bei mir hat er beim import gemeckert das keine id vorhanden ist. Die muss eigenlitch `_id` sein, aber in den daten ist die ìd` so drin

**Comment by Gompman** [comment]
Du hattest recht. Irgendwie fehlte das _ID
{
  "from": "system.adapter.knx.0",
  "ts": 1531581164377,
  "common": {
    "name": "OG-Büro-Deckenbeleuchtung-schalten",
    "type": "boolean",
    "role": "level",
    "min": 0,
    "max": 1,
    "read": false,
    "write": true
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "0/1/24",
    "addressRefId": "P-0546-0_GA-295",
    "statusGARefId": "P-0546-0_GA-301",
    "actGARefId": ""
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.Licht.Schalten_(Ein_Aus).OG-Büro-Deckenbeleuchtung-schalten",
  "type": "state"
}

**Comment by Scrounger** [comment]
Der Datenpunkt wird doch aber vom Adapter erstellt?
Wenn ja dann infomier mal den entwickler das da was nicht stimmt.

Heißt ich kann den Punkt hier schließen?

**Comment by Gompman** [comment]
Ist das erste Widget welches sich so verhält. Habe derzeitig die Vis mit dem Material Design von uhula ohne dieses Verhalten in Betrieb. Werde es mit einem nicht KNX Datenpunkt testen. Melde mich dann noch einmal bei dir. Danke erstmal für das schnelle Feedback.

**Comment by Gompman** [comment]
Also anscheinend verhalten sich alle Widgets genau so. Da ich aber von Anfang an das Uhula Material Design nutze funktioniert es mit den Darstellungen.

Interessant werde das mal an den Entwickler weitergeben.
Kann also ersteinmal geschlossen werden.
