### ISSUE TITLE
[Line History Chart] Individuelle Intervalle (Feature Request)

### ISSUE THREAD

**Issue by Mic-M** [Scrounger/ioBroker.vis-materialdesign#65]
Feature Request:
Wäre schön, wenn man individuelle Zeitintervalle per Millisekunden setzen könnte.
Also nicht nur die Vorgabe-Werte [von hier](https://github.com/Scrounger/ioBroker.vis-materialdesign/blob/235530e4e54346b5527333ca06ce596519954c67/widgets/materialdesign/js/materialdesign.chart.js#L802). 
Dann könnte man z.B. "10 Tage" oder z.B. sogar "7 Tage minus aktuelle Uhrzeit" setzen (wenn man dieses Intervall in VIS per JavaScript berechnet), damit das Chart ab 0:00 Uhr startet.
Danke.

**Comment by Scrounger** [comment]
Nette Idee.
Und das individuelle Zeitinterval würde dann in einem Datenpunkt stehen?

**Comment by Mic-M** [comment]
Ja, so die Idee :-)

**Comment by Scrounger** [comment]
Umgesetzt in 3aa88061242e6b80b5f822c290019295b4dfcf43

Der Datenpunkt muss dann vom typ 'number' sein und man muss nicht das zeitinterval angeben sondern den timestamp (in ms) des starts des graphs - also ein Datetime in ms
