### ISSUE TITLE
Some Widgets disappear after a few seconds

### ISSUE THREAD

**Issue by tony63526** [Scrounger/ioBroker.vis-materialdesign#66]
I have insertet a View in 8 Widget 
and implementet a picture.
After starting the runtime to see the widget in fullscreen the picture is gone after 
32 seconds.

**Comment by Scrounger** [comment]
View in Widget 8 ist Not Part of thus Adapter.
Set the persistent checkbox in enabled. If the problem still exist pleased Report thus to the vis adapter.
