### ISSUE TITLE
[Line History Chart] JSON-State als Quelle (Feature Request)

### ISSUE THREAD

**Issue by Mic-M** [Scrounger/ioBroker.vis-materialdesign#67]
Bitte siehe hier: https://forum.iobroker.net/post/389213

Gewünscht ist, dass das Widget nicht nur Daten einer History-Instanz als Quelle nimmt, sondern auch ein gegebenes Array aus Werten, also typischerweise per JSON von einem Datenpunkt.

Damit könnte nicht nur eine aufgezeichnete Historie im Widget dargestellt werden, sondern beliebige Werte, die von einem Datenpunkt stammen.

Danke!

**Comment by Scrounger** [comment]
JSON Chart Widget hinzugefügt -> 37230f037d03ebc0b4c0be48823ef7fa114f550b
