### ISSUE TITLE
Typo im Line History Chart

### ISSUE THREAD

**Issue by Steff42** [Scrounger/ioBroker.vis-materialdesign#70]
Hallo,
mir sind im Line History Chart bei den Einstellungen zwei kleinere Typos aufgefallen. Beides mal ist anstatt "Titel" "Ttiel" angegeben.

Einmal hier:
![image](https://user-images.githubusercontent.com/35137293/78687120-223d0880-78f4-11ea-82d7-9137b6e357aa.png)
Und dann noch hier
![image](https://user-images.githubusercontent.com/35137293/78687179-34b74200-78f4-11ea-8f7c-aeb111523b76.png)

Gruß Steffen

**Comment by Scrounger** [comment]
Danke, hab ich gefixt
