### ISSUE TITLE
Erweitern des Select/Input-Widgets um den Typ 'number'

### ISSUE THREAD

**Issue by darkiop** [Scrounger/ioBroker.vis-materialdesign#72]
https://forum.iobroker.net/topic/29666/material-design-widgets-input-select-autocompl/44

**Comment by Scrounger** [comment]
@darkiop 
Bitte aktuell gut Version testen, v0.3.1.

**Comment by darkiop** [comment]
fixed, Danke dir!

**Comment by darkiop** [comment]
@Scrounger Mir ist gerade aufgefallen, das mit der 0.3.1 einige meiner Buttons in der VIS nicht mehr funktionieren. Hatte noch keine Zeit genauer zu schauen, aber es müssten alles buttonToggle gewesen sein - mit der IconList und als getrennter Button. Nach der Installation hatte ich nochmals einen manuellen Upload des VIS und auch deines Adapters vorgenommen. Bei Bedarf kann ich Morgen mal ins Browserlog schauen mit der 0.3.1 - nach dem Downgrade auf die 0.3.0 funktionieren die Buttons wieder wie gewohnt.

**Comment by Scrounger** [comment]
@darkiop 
Hatte ich hier ja geschrieben:
https://forum.iobroker.net/topic/32018/test-adapter-material-design-widgets-v0-3-x/20

Hab bei allen Widgets - auch bei den buttons - jetzt eingeführt, dass er schaut von welchen typ der Datenpunkt ist und entsprechend dann umwandelt.
Da muss jetzt intensiv getestet werden ;-)

**Comment by Scrounger** [comment]
@darkiop :
Hab den Fehler glaub gefunden. Lad dir die aktuelle version. Danach ein iobroker upload vis durchführen!

**Comment by darkiop** [comment]
Erster Test erfolgreich. Ich beobeobachte das.

**Comment by darkiop** [comment]
Da passt doch noch etwas nicht, mit der github Version gibt es einen Berechtigungsfehler beim Icon toggle:

![2020-04-16 13_41_22-Window](https://user-images.githubusercontent.com/205119/79467539-248f1900-7ffe-11ea-8dda-2aead0ee0034.png)

**Comment by Scrounger** [comment]
@darkiop 
Das hat aber nix mit den Widgets zu tun sondern mit der Berechtigung des hinterlegten Datenpunktes

**Comment by darkiop** [comment]
Hm, das sind DPs welche alle auf diese Art und Weise angelegt werden:

`createState("Szenen.Szene_Spotify", { name: 'Szenen.Szene_Spotify', "role": "button", "type": "mixed", "read": true, "write": true, "smartName": { "de": "Szene Spotify", "smartType": "SWITCH" } });`

Berechtigungen schauen so aus:

![grafik](https://user-images.githubusercontent.com/205119/79482913-cec46c00-8011-11ea-9745-214d3fad6a8a.png)

Mit der 0.3.0 funktioniert das ganze wie erwartet. Sicher das es an den Berechtigungen liegt?

**Comment by Scrounger** [comment]
OK welches Widget genau? Bitte exakten Bezeichner aus bis Editor angeben

**Comment by darkiop** [comment]
![grafik](https://user-images.githubusercontent.com/205119/79485118-fd901180-8014-11ea-89f6-ddc7191a7990.png)

**Comment by Scrounger** [comment]
> `createState("Szenen.Szene_Spotify", { name: 'Szenen.Szene_Spotify', "role": "button", "type": "mixed", "read": true, "write": true, "smartName": { "de": "Szene Spotify", "smartType": "SWITCH" } });`

> Mit der 0.3.0 funktioniert das ganze wie erwartet. Sicher das es an den Berechtigungen liegt?

Denke schon, weil diese Meldung nur erscheint wenn da was nicht passt.
Evtl. liegt es aber auch an dem `type: mixed` muss ich testen.

Stell mir bitte die raw daten des datenpunktes zur Verfügung.

**Comment by darkiop** [comment]
Also ich habe eben nochmal ein paar DPs durchgeschaut, die werden im Standard alle mit diesen Berechtigungen angelegt.

Hier die raw daten:

`{
  "from": "system.adapter.javascript.0",
  "user": "system.user.admin",
  "ts": 1586459717220,
  "common": {
    "name": "Szenen.Szene_Spotify",
    "role": "button",
    "type": "mixed",
    "read": true,
    "write": true,
    "smartName": {
      "de": "Szene Spotify",
      "smartType": "SWITCH"
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "javascript.0.Szenen.Szene_Spotify",
  "type": "state"
}`

**Comment by Scrounger** [comment]
@darkiop 

Also da war noch nen Fehler drin, allerdings hat er beim mir nicht die Meldung angezeigt.
Bitte nochmal testen.

Noch ein Tipp: Wenn du einen Button realsierst, dann solltest du Widget Button State nehmen mit Wert 'true'.

**Comment by darkiop** [comment]
Danke, das sieht gut aus. Und auch danke für den Hinweis mit den Button State - hab ich korrigiert. Ich teste Morgen das ganze noch etwas und schließe hier dann.

**Comment by darkiop** [comment]
Bisher nichts mehr aufgefallen.
