### ISSUE TITLE
Toggle Widget ohne Funktion

### ISSUE THREAD

**Issue by Coffee-lover** [Scrounger/ioBroker.vis-materialdesign#74]
Hi,
unter Version 0.3.1. können Toggle-Elemente (Switch, Button toggle vertical, Button toggle  ) nicht mehr geschalten werden. Die Werte ändern sich abhängig von den Datenpunkten, aber Änderungen werden nicht an den DP übergeben. Umschalttyp (Boolean / Wert) haben keinen Einfluss, die Auswahl "nur lesend" wurde aktiv und inaktiv getestet - ändert nichts.

VG

**Comment by Scrounger** [comment]
0.3.1 ist alpha version. Problem wurde bereits in #72 bearbeitet und gefixt.
Fix kommt mit der 0.3.2.
