### ISSUE TITLE
CSS-Probleme in 0.3.2

### ISSUE THREAD

**Issue by DevChannel-de** [Scrounger/ioBroker.vis-materialdesign#75]
Nach der Installation von 0.3.2 sehe ich Styling-Probleme. In der Konsole sieht man diese Pfade:
![image](https://user-images.githubusercontent.com/57469720/79874932-3c451380-83e9-11ea-94cb-a3605e89094e.png)

Danke im Voraus :-)

**Comment by Scrounger** [comment]
fixed in v0.3.3
