### ISSUE TITLE
Semikolon als Trennzeichen im Select-Widget erlauben

### ISSUE THREAD

**Issue by Starcon79** [Scrounger/ioBroker.vis-materialdesign#76]
Wie im Forum besprochen würde ich dich bitten das Semikolon als Trennzeichen in der Werteliste vom Select-Widget zu erlauben da es standardmäßig als Trennzeichen in Iobroker genutzt wird.

![Werteliste](https://user-images.githubusercontent.com/38224290/80332662-b9d6ac80-884b-11ea-9a8f-06e1540ad222.png)

Vielen dank schon mal.

**Comment by Scrounger** [comment]
in c15e0522dc6dd555bc781a3bc8bc913b4ba1b7d5 enthalten
