### ISSUE TITLE
Lock-Option at Switch Widget

### ISSUE THREAD

**Issue by Bodengriller** [Scrounger/ioBroker.vis-materialdesign#79]
Could you please add the possibility to lock the switch-widget like the button state widget?

I like these small slider switches, but there are a few switch points (e.g. the power outlet of the 3D printer) where I would like to add a second safety to avoid accidental power off.

**Comment by Scrounger** [comment]
in 090a3dffca173c90594c84b68a846de6491ecd7b enthalten
