### ISSUE TITLE
Value Select nicht angezeigt beim Zugriff über https://iobroker.net/

### ISSUE THREAD

**Issue by DevChannel-de** [Scrounger/ioBroker.vis-materialdesign#8]
Hi,
bei tplVis-materialdesign-Select-Value, nur beim Zugriff über iobroker.net, bekomme ich folgenden Fehler:
![image](https://user-images.githubusercontent.com/57469720/68354609-2f6b8680-010d-11ea-844f-2557cf765a41.png)

Wenn ich auf die gleiche View / Widget im lokalen Netzwerk zugreife, läuft alles ok.

Danke im Voraus :-)

**Comment by sigi2345** [comment]
Kann ich bestätigen.

**Comment by Scrounger** [comment]
Tritt das nur beim Widget select value auf oder auch bei anderen Widgets?

**Comment by DevChannel-de** [comment]
Ich habe nicht alle Widgets getestet aber doch schon einige...
Das Problem, dass ein Widget komplett "verschwindet", ist mir aber nur bei den beiden Selects aufgefallen.

**Comment by sigi2345** [comment]
> Tritt das nur beim Widget select value auf oder auch bei anderen Widgets?

Vis starte gar nicht unter Pro.

![Screenshot (513)](https://user-images.githubusercontent.com/41079106/68396241-873bd900-0171-11ea-9621-b681765a9e8d.png)

**Comment by Scrounger** [comment]
@Apollon77:
Kann es sein das iobroker.pro nicht den befehl console.exception kennt?

**Comment by Scrounger** [comment]
closed because of inactivty
