### ISSUE TITLE
[Enhancement] Input Widget - Eingabe zentriert

### ISSUE THREAD

**Issue by Maja61** [Scrounger/ioBroker.vis-materialdesign#80]
Hallo,

ist es möglich die Eingabefelder des Input-Widget zentriert darzustellen?
Siehe [link](https://forum.iobroker.net/topic/29666/material-design-widgets-input-select-autocompl/65)

danke + gruß

**Comment by Scrounger** [comment]
5a2b1d05d5fe9b2954c7b1f5b1be9b141d6c0311
