### ISSUE TITLE
[Erweiterung] Multiwidget Button

### ISSUE THREAD

**Issue by sigi2345** [Scrounger/ioBroker.vis-materialdesign#81]
Ein Multi-Button-Widget wäre Super!  

Forum:
wäre es möglich mit einem Button State, mehrere DP auf einmal Werte zu setzen?

https://forum.iobroker.net/topic/29664/material-design-widgets-buttons-widget/56

**Comment by Scrounger** [comment]
enthalten in 7e1476891cc06bc32ec5d18b3b31319c4ab2eb03
