### ISSUE TITLE
Dialog-Widget öffnet nicht in der Mitte des Bildschirms

### ISSUE THREAD

**Issue by Starcon79** [Scrounger/ioBroker.vis-materialdesign#82]
Hallo wie im Forum besprochen (https://forum.iobroker.net/topic/31870/material-design-widgets-dialog-view-widget/18) öffnet das Dialog-Widget bei mir nicht in der Mitte des Bildschirms.

**Comment by Scrounger** [comment]
In https://github.com/Scrounger/ioBroker.vis-materialdesign/tree/0.3.9 gefixt
