### ISSUE TITLE
[Button] doppelte Ausführung bei Touch

### ISSUE THREAD

**Issue by micklafisch** [Scrounger/ioBroker.vis-materialdesign#83]
Hallo,
ich habe das Problem, dass die Buttons (z.B. Button Addition) doppelt am iPad ausgeführt werden. Ich kann das im Firefox mit "Bildschirmgröße testen" auch nachstellen, sobald die Berührungssimulation aktiv ist, wird jeder "klick" doppelt auf den Buttons ausgeführt.

Ist das bekannt oder kann das jemand bestätigen?

**Comment by Scrounger** [comment]
hab in https://github.com/Scrounger/ioBroker.vis-materialdesign/releases/tag/0.3.9 was eingebaut, das das jetzt verhindern sollte.
Bitte testen und Rückmeldung geben, da ich den Fehler nicht reproduzieren kann

**Comment by micklafisch** [comment]
Hi,
ich habe das Update geladen, am iPad ist der Fehler nun nicht mehr. Im Firefox unter Bildschirmgröße testen ist er zwar noch vorhanden, aber dies ist ja eh nur eine "Testumgebung" und nicht weiter tragisch. Wichtig ist die Fehlerbehebung am iPad und das klappt jetzt prima. 

Vielen Dank.
