### ISSUE TITLE
Fully Browser

### ISSUE THREAD

**Issue by skokarl** [Scrounger/ioBroker.vis-materialdesign#85]
eins vorab... Du machst einen super JOB !!!

hab vorhin auf die 0.3.9 aktualisiert.
Jetzt reagiert die Häflte meines Tablets nicht mehr.
Am Laptop mit Firefox alles okay, am Tablet mit Fully Browser keine Reaktion mehr auf der Hälfte des Bidschirms ( deine Buttons )
Zurück auf die 0.36, wieder alles gut.
Du musst etwas gravierendes geändert haben.

**Comment by Scrounger** [comment]
Einzige größere Änderung gab's am list Widget, was nach meinen Test eigentlich keine großen Auswirkungen haben sollte (Firefox & Chrome).

Hast du nen eustart gemacht bzw nen iobroker Upload vis?
Was steht im consolen Log?
Bitte zukünftig immer gleich mit anhängen ohne ist es unmöglich für mich nen Fehler Analyse durchzuführen!

**Comment by skokarl** [comment]
Mach hier zu, was da passiert kann ich nicht nachvollziehen. Und Konsole etc. kann ich Dir nicht anbieten, hab das nur auf dem Tablet. Fakt ist, 0.36 geht einwandfrei. 039 geht am Laptop im Firefox und Chrome einwandfrei, auf dem Tablet keine Reaktion der Navi Buttons. Weder im Chrome direkt noch im Fully. Ganz ganz komisch. Ist mir klar, dass Du mir da nicht helfen kannst, vielleicht meldet sich noch jemand anderes der auch ein Samsung Tab nutzt, oder Dir fällt plötzlich doch noch was ein was Du geändert hast und das Tablet ärgern könnte. Danke Dir.

**Comment by Scrounger** [comment]
Aber dann muss ich da ja nen fehler drin haben, wenn es mit 0.3.6 alles geht.
Ich hab an vielen Kleinigkeiten gearbeitet, die eigentlich keinen großen einfluss haben sollten.
Welches Widget meinst du mit Navi Buttons genau? Button State, Button Navi, etc. Brauch hier exakte angaben. Weil an den Buttons hab ich was geändert.

Wie du an die console bei chrome android kommst ist hier gut beschrieben:
https://dev.to/dev0x0/using-google-chrome-console-on-any-mobile-device-9ec

Versuch doch mal ob du an das log damit kommst.

**Comment by skokarl** [comment]
Es geht um den Button Navigation. Vielleicht nicht der einzigste, aber der erste der auffällt weil ich ihn sehr oft benutze. Mehr konnte ich nocht nicht testen, geht ja nix. :-( Tablet hängt fest verbaut an der Wand, versuche mir aber ne USB Verlängerung zu besorgen, und dann gucke ich ob ich irgendwas finde was hilft, oder das log hinkriege. Vom Gefühl her würde ich sagen, der Button erkennt die Berührung, tut dann aber nix. Melde mich sobald ich was habe.

**Comment by Scrounger** [comment]
Debugging geht bei Chrome auch über netzwerk:
https://developers.google.com/web/tools/chrome-devtools/remote-debugging

**Comment by skokarl** [comment]
Danke für Deinen Einsatz, ich habs versucht, aber ich bin völlig überfordert. Ich weiß gar nicht was ich tue. Links waren super, habs auch verstanden, aber bei der Konsole weiß ich nicht mehr weiter. Hab die 0.39 eben nochmal probiert, keine Chance, Button Toogle geht, Butoon Navigation nicht. Die müssen sich irgendwie unterscheiden. Vielleicht finde ich jemand der mal remote zu mir kommt, und dann versucht an die Konsole vom Tablet zu kommen. Mach Dir keine Gedanken, ist alles gut, vielleicht liegt es am Tablet.

**Comment by skokarl** [comment]
Danke, dass Du soviel Zeit für mich geopfert hast, aber ich kriegs nicht hin. Ich kriege keinen connect aufs Tablet, weder mit WLAN noch mit USB. Ist aber auch nicht verwunderlich, sogar die DEV's im Netz haben mit Win10 und den Samsungs Tablets ne Menge Ärger, und ich bin nur ein Anfänger, keine Chance. Samsung und Chrome mögen sich nicht, und der Fully Browser ist ja auch Chrome. Das einzigste was mir noch aufgefallen ist, Dein Toogle Button funktioniert, der Navigations Button nicht.... die beiden haben also einen entscheidenden Unterschied den sie früher nicht hatten.

**Comment by arteck** [comment]
ich habs auch.. aber auch wenn du in chrome auf Android es machst dann reagieren die button nicht mehr.. entprellzeit vielleicht ?? @Scrounger

**Comment by skokarl** [comment]
@arteck  Du hast das Problem auch....oder nicht ? Hast Dich gerade bisschen unglücklich ausgedrückt, ... also auch Fully und Chrome ?

**Comment by Scrounger** [comment]
Teste bitte die aktuelle github version 0.3.10
Hab u.a. jetzt Sentry eingebaut, d.h. bei Fehlern müsste ich die direkt dann sehen.

**Comment by skokarl** [comment]
Super !!! geht wieder. Und jetzt nur Interesse halber.... was war in der 0.39 das Problem ?
