### ISSUE TITLE
[Line History Chart] Aggregation, Count für jeden Datensatz indivduell festlegen

### ISSUE THREAD

**Issue by fu-zhou** [Scrounger/ioBroker.vis-materialdesign#87]
Hallo, es scheint, als wenn das Widget "Line History Chart" Binärwerte nicht darstellt, weil es true-false nicht als 1-0 interpretiert.
Ich würde gerne "Regen" zeigen und habe den Datenpunkt auch angebunden, er wird aber nicht dargestell.
![Zwischenablage02](https://user-images.githubusercontent.com/11984960/82760487-0d5cfb80-9df4-11ea-915a-a1afd273d7cd.jpg)

Für den Datenpunkt habe ich eine eigene y-Achse definiert, so dass es nicht an der Auflösung liegen kann.
![Zwischenablage04](https://user-images.githubusercontent.com/11984960/82760527-52812d80-9df4-11ea-8c97-86d79ffda946.jpg)

**Comment by Scrounger** [comment]
Bei mir funktioniert es:
![grafik](https://user-images.githubusercontent.com/6370451/83253936-2677fa80-a1ae-11ea-99e4-3e98e3d3d187.png)

Welche history instanz verwendest du?
Was wird in der Datenbank abgespeichert true/false oder 0/1?
Was steht in der console log (debug modus des Widget davor aktivieren!)?
Welcher browser?

**Comment by fu-zhou** [comment]
Bei mir geht's jetzt auch: "Allgemein" - "Aggregation" war auf "Mittelwert", was für die Temperaturen gut ist, aber den Regen (true-false) dann nicht anzeigt. Habe auf "Min-Max" umgestellt, was jetzt etwas "nervöse" Temperatur-Verläufe zeigt, aber Regen ist mit da.

Hier noch zu deinen Fragen:
sql.0
true-false
Console log habe ich mir jetzt gespart
Opera+Chrome

**Comment by Scrounger** [comment]
Ok dann wäre es wohl sinnvoller das man für jeden datensatz die aggregation einzeln festlegen kann, anstatt für alle im Widget. So ist es auch beim Flot gelöst.

**Comment by fu-zhou** [comment]
Klingt gut, danke!

**Comment by Scrounger** [comment]
in 0cb37d481ece6d9e859ddee42393d4145d2f16b5 enthalten. 
siehe doku https://github.com/Scrounger/ioBroker.vis-materialdesign#line-history-chart
