### ISSUE TITLE
[Enhancement] Slider Widget Anzeigewert manipulieren

### ISSUE THREAD

**Issue by sk8er-boi90** [Scrounger/ioBroker.vis-materialdesign#88]
Es wäre toll, wenn man den Anzeigewert des Sliders beeinflussen könnte. Beispiel  Rolladen wird über einen Wert von 0 bis 1 gesteuert. Anzeige sollte dann 0-100% sein.

**Comment by Scrounger** [comment]
Prozent oder realer Wert, wie beim Progress Widget

**Comment by Scrounger** [comment]
enthalte in 1db28ec758050bf1979507a2b2e8cabb2934462f
