### ISSUE TITLE
[Calendar] Kalenderwoche in Monatsansicht

### ISSUE THREAD

**Issue by andreasheins** [Scrounger/ioBroker.vis-materialdesign#89]
Kalenderwoche in der Monatsansicht einblenden

![image](https://user-images.githubusercontent.com/54315670/82830366-d0f1d400-9eb5-11ea-985f-be4ecc3505a1.png)

**Comment by Scrounger** [comment]
Wird seitens Vuetify API noch nicht unterstützt, kommt mit v2.3.0

https://github.com/vuetifyjs/vuetify/issues/9117
