### ISSUE TITLE
discrete slider: initDelay too low?

### ISSUE THREAD

**Issue by DevChannel-de** [Scrounger/ioBroker.vis-materialdesign#9]
Sometimes the slider knob isn't on the right position but instead it's positioned at the beginning of the line and it cannot be moved to the right direction again:
![image](https://user-images.githubusercontent.com/57469720/68553244-c7c07e80-041f-11ea-92a8-d7981105ecc2.png)

After some investigations I found out that increasing the value of initDelay solves this issue, i.e. from default value 250 to 500. Is this the right solution and should maybe the default be increased so that others don't need to search for same solution?

**Comment by Scrounger** [comment]
Yeah but ohters need a value of 750 or 1000. So there will nor an all working value for all out there.
i increased it to 500.

**Comment by DevChannel-de** [comment]
Sorry for coming back to this point again, but maybe one idea could stabilize it for every use case and would make this value in editor obsolete:
AFAIK, currently you're using the initDelay value within a `setTimeout` function.
Do you see a possibility to implement an upfront loop that checks the initialization x times (let's say 10 times a 250 msec) and continue only if the component/data is in place?
If after 10 times (=2,5 sec) the needed data is still not in place, a rendering of the slider would be cancelled entirely.

**Comment by Scrounger** [comment]
Still tried this solution, but IT mir works because of Font geht a Response fromm the Slider If it ist ready. This ist a Bug in the api.
Best solution would bei to geht the information If Dom ist ready drin the bis runtime. But didnt find a was to geht this information from vis. Document.load / .ready Not working
