### ISSUE TITLE
Progress Bar: 'Wert umkehren' funktioniert nicht mehr

### ISSUE THREAD

**Issue by mhtl** [Scrounger/ioBroker.vis-materialdesign#92]
Wahrscheinlich seit Version 0.3.11, keine Auswirkung bei anhacken von 'Wert umkehren'.

**Comment by Scrounger** [comment]
Bug in Vuetify API. Wird in v 2.3.0 gelöst sein.
https://github.com/vuetifyjs/vuetify/issues/11245
