### ISSUE TITLE
[Button] Multistate Button Verzögerung

### ISSUE THREAD

**Issue by m-s-b** [Scrounger/ioBroker.vis-materialdesign#93]
Ist es möglich eine, gerne auch konfigurierbare, Verzögerung beim setzen der einzelnen States einzubauen?  Muss die States mit einer Verzögerungen an den Fernseher senden, es werden sonst nicht alle akzeptiert.

**Comment by Scrounger** [comment]
Auf die Idee meinen TV damit zu steuern bin ich noch gar net gekommen, top.
Dafür braucht man die Verzögerung, Werd ich also einbauen

**Comment by Scrounger** [comment]
enthalten in 488b75d9926feb2d2ec31468171ad12d78f5037a
