### ISSUE TITLE
Version 0.3.15

### ISSUE THREAD

**Issue by matze8925** [Scrounger/ioBroker.vis-materialdesign#97]
Hi zusammen,
habe das Problem das meine Vis Runtime nicht mehr startet seit Update Materialdesign auf 0.3.15
Es kommt nur noch:
Verbinde mit dem Server Lade Werte...
Der Editor Läuft ganz normal ? nur die Vis Runtime nicht 

Habe alles Versucht... Mehrere Neustarts, Adapter Deinstalliert, Downgrade, Widgets im Editor Gelöscht, Cache von mehreren Verschiedenen Geräten/Browsern gelöscht usw... 
Sobald der Adapter Materialdesigns Deinstalliert ist Läuft auch die Vis Runtime wieder, nur gibt es dann logischerweise keine Material-Widgets mehr.

Ein Downgrade ist eben auch nicht Möglich... laut Github ist 0.3.14 die Aktuellste, ich habe aber 0.3.15???
Wenn ich Versuche zu downgraden kommt :

$ ./iobroker upgrade vis-materialdesign@0.3.14
Adapter "vis-materialdesign" is not in the repository and cannot be updated.
process exited with code 0

Eine direkte Installation auf eine ältere Version habe ich bisher nicht geschafft, sobald ich https://github.com/Scrounger/ioBroker.vis-materialdesign installiere springt er direkt auf Version 0.3.15.

Kann hier bitte jemand helfen?? komme nicht mehr weiter :(
Danke schon mal

**Comment by Scrounger** [comment]
Die Version 0.3.15 ist alpha und nicht im latest released, d.h. da kann es natürlich sein das etwas noch nicht funktioniert.
Was steht im browser consolen log (F12) zur runtime?

Auf alter version wechseln:
![version](https://user-images.githubusercontent.com/6370451/84592076-1feeb180-ae43-11ea-9844-ad703645cf31.gif)

**Comment by matze8925** [comment]
Habs nach langen Probieren hinbekommen zu downgraden. 
Im Admin bei Einstellungen von Default auf latest stellen, dann geht der downgrade warum auch immer ...anschließend wieder auf default zurückgestellt.

Danke für den Denkanstoß :)
