### ISSUE TITLE
[Select] "Position" Property

### ISSUE THREAD

**Issue by gaga191281** [Scrounger/ioBroker.vis-materialdesign#99]
Bei dem Listenwidget "Select" kann unter dem Punkt "Menü-Layout" für die Property "Position" die Öffnungsrichtung für die Liste eingestellt werden. (Oben, Unten, Auto).
Egal welchen wert man wählt. Beim ersten Öffnen wird die Liste anders als eingestellt geöffnet. Bei Listen, die am oberen oder unteren Rand der UI platziert sind führt das dazu, dass einige Elemente der Liste beim ersten Öffnen  außerhalb des Viewports liegen. Schließt man die Liste wieder und öffnet sie erneut, wird sie richtig angezeigt.
Das Fehlverhalten tritt bei jedem neu Laden der View auf.

Adapter Version: 0.3.19
JS-Controller Version: 3.1.6
Node Version: 12.8.2
OS: Ubuntu 18.04.4 Server

**Comment by Scrounger** [comment]
Kann das weder mit firefox oder chrome reproduzieren.
Bitte nen Beispiel Projekt bereit stellen, wo das phänomen auftritt.

Welchen Browser verwendest du?
Was steht in der browser console (F12), wenn das Mneu falsch öffnet?
